import {
  FileCIcon,
  FileCodeIcon,
  FileCppIcon,
  FileCssIcon,
  FileCsvIcon,
  FileHtmlIcon,
  FileIcon,
  FileJpgIcon,
  FileJsIcon,
  FileJsxIcon,
  FileLockIcon,
  FileMdIcon,
  FilePdfIcon,
  FilePngIcon,
  FilePyIcon,
  FileRsIcon,
  FileSqlIcon,
  FileSvgIcon,
  FileTextIcon,
  FileTsIcon,
  FileTsxIcon,
  FileVueIcon,
  FileZipIcon,
  FileImageIcon,
} from "@phosphor-icons/react";
import { pathParts } from "@ace/ui-core";
import type { IconGlyph } from "@/components/icon.tsx";

const byExtension: Record<string, IconGlyph> = {
  ts: FileTsIcon,
  mts: FileTsIcon,
  cts: FileTsIcon,
  tsx: FileTsxIcon,
  js: FileJsIcon,
  mjs: FileJsIcon,
  cjs: FileJsIcon,
  jsx: FileJsxIcon,
  css: FileCssIcon,
  html: FileHtmlIcon,
  md: FileMdIcon,
  mdx: FileMdIcon,
  py: FilePyIcon,
  rs: FileRsIcon,
  sql: FileSqlIcon,
  svg: FileSvgIcon,
  png: FilePngIcon,
  jpg: FileJpgIcon,
  jpeg: FileJpgIcon,
  gif: FileImageIcon,
  webp: FileImageIcon,
  vue: FileVueIcon,
  c: FileCIcon,
  h: FileCIcon,
  cpp: FileCppIcon,
  cc: FileCppIcon,
  csv: FileCsvIcon,
  pdf: FilePdfIcon,
  zip: FileZipIcon,
  gz: FileZipIcon,
  tgz: FileZipIcon,
  lock: FileLockIcon,
  txt: FileTextIcon,
  json: FileCodeIcon,
  yml: FileCodeIcon,
  yaml: FileCodeIcon,
  toml: FileCodeIcon,
  sh: FileCodeIcon,
  go: FileCodeIcon,
  swift: FileCodeIcon,
  kt: FileCodeIcon,
  java: FileCodeIcon,
};

/** A file's glyph from its extension: shape only, the tree stays monochrome. */
export function fileIcon(path: string): IconGlyph {
  const name = pathParts(path).name.toLowerCase();
  const dot = name.lastIndexOf(".");
  return (dot >= 0 && byExtension[name.slice(dot + 1)]) || FileIcon;
}
