import { writeFileSync } from "node:fs";
import { compileToSource, mergeConfigs } from "cn/compiler";
import { defaultConfig } from "cn/config";
import { cnExtension } from "../src/lib/cn-extension.ts";

/*
 * Compiles the class-merge tables for the app's Tailwind config once, so the page loads
 * `cn/engine` with ready tables instead of `cn/config`, which compiles them at startup (more
 * code on the first paint and a slower first call). Run after upgrading `cn` or changing
 * `cn-extension.ts`: `bun run --filter @ace/web cn:tables`.
 */
const out = new URL("../src/lib/cn-tables.gen.ts", import.meta.url);
const source = compileToSource(mergeConfigs(defaultConfig(), cnExtension), {
  lang: "ts",
  banner:
    "// Generated by apps/web/scripts/cn-tables.ts from src/lib/cn-extension.ts. Do not edit.",
});
writeFileSync(out, source);
process.stdout.write(`wrote ${out.pathname}\n`);
