import { mutations, checkMutations } from "./mutations.ts";
await checkMutations([
  ...mutations,
  {
    name: "Persist offset zero",
    file: "upload-store.ts",
    before: "row.offset += bytes.length;",
    after: "row.offset = 0;",
    test: "uploads.test.ts",
    behavior: "daemon restart preserves",
  },
  {
    name: "Accept changed retries",
    file: "upload-store.ts",
    before: "read.bytesRead === bytes.length && previous.equals(bytes)",
    after: "true",
    test: "uploads.test.ts",
    behavior: "retrying identical chunks",
  },
  {
    name: "Remove chunk fsync",
    file: "upload-store.ts",
    before: "await (this.options.syncChunk ? this.options.syncChunk(file) : file.sync());",
    after: "void file;",
    test: "uploads.test.ts",
    behavior: "failed durability barrier",
  },
  {
    name: "Disable Claude image",
    file: "projection.ts",
    before: 'if (image) return { type: "image", source };',
    after: 'if (false) return { type: "image", source };',
    test: "projection.test.ts",
    behavior: "Claude receives image",
  },
  {
    name: "Break OpenCode URL",
    file: "projection.ts",
    before: "url: fileUri(a.path)",
    after: 'url: "broken"',
    test: "projection.test.ts",
    behavior: "OpenCode receives file",
  },
  {
    name: "Disable ACP resources",
    file: "projection.ts",
    before: "capabilities.embeddedContext && capabilities.documents.includes(a.mimeType)",
    after: "false",
    test: "projection.test.ts",
    behavior: "ACP receives embedded resources",
  },
  {
    name: "Remove fallback diagnostics",
    file: "projection.ts",
    before: "diagnostics.push(",
    after: "[].push(",
    test: "projection.test.ts",
    behavior: "missing bytes and unsupported",
  },
  {
    name: "Remove socket overlap rejection",
    file: "apps/daemon/src/server.ts",
    before: "!options.context || contextBusy",
    after: "!options.context",
    test: "apps/daemon/src/context.server.process.test.ts",
    behavior: "socket rejects overlapping",
  },
  {
    name: "Retain deleted indexed files",
    file: "git-workspace.ts",
    before: "this.index.update(path, false);",
    after: "void path;",
    test: "mentions.test.ts",
    behavior: "incremental index updates",
  },
  {
    name: "Inflate PNG before dimension rejection",
    file: "media.ts",
    before: "const image = inspectImage(header, trailer, bytes, limits);",
    after:
      'if (sniffMime(header) === "image/png") (await import("node:zlib")).inflateSync(header.subarray(41, 41 + header.readUInt32BE(33)));\n    const image = inspectImage(header, trailer, bytes, limits);',
    test: "uploads.test.ts",
    behavior: "oversized PNG dimensions take precedence",
  },
  {
    name: "Skip WebP container validation",
    file: "image-container.ts",
    before: 'if (mime !== "image/png" &&',
    after: 'if (mime === "image/webp") return;\n  if (mime !== "image/png" &&',
    test: "uploads.test.ts",
    behavior: "WebP frame dimensions|WebP framing",
  },
  {
    name: "Omit composed attachments",
    file: "service.ts",
    before: "for (const blob of lease.blobs)",
    after: "for (const blob of lease.blobs.slice(0, 0))",
    test: "service.test.ts",
    behavior: "composer resolves mentions",
  },
]);
