/** Small flat pictures standing in for what ace's tools capture: never anyone's real screen. */

/** A Safari window on a sign-in page, as `screen_screenshot` returns it. */
export const safariShot =
  "iVBORw0KGgoAAAANSUhEUgAAAUAAAADICAIAAAAWZq/8AAAC2klEQVR42u3asQnCQACG0czhBFZOkEJwCEuHcD0HsE7hACmC" +
  "IKSwDGJsQziOWJzcmff4y1QxH4ScVd8/zazQVW6BmYDNTMBmJmAzAa9xbdtZ/vOgCljAAl5BwOPpOF3kyvdlN13kyu11P52A" +
  "TcBJAp7VG2l4Vm+k4Vm9uTWsDQH/ScDBeoMNB+sNNhysN6uGtSFgAQvYBCxgAZuABSxgAQtYwCZgX6F9hTYBOwcWsIDNP7EE" +
  "LGABC9gELGAzE7CZgM1MwGaWPOCmuZlZoatGoFgCBgEDAgYEDAIGBAwIGBAwCBgQMCBgEDAgYEDAgIBBwICAAQEDAgYBAwIG" +
  "BAwCBgQMCBgQMAgYEDAgYEDAIGBAwICAQcCAgAEBAwJObhhetnweGAELWMACRsACFjCaFLCABSxgBCxgAQuYr9T1YVUTsIAF" +
  "LGAE7BXaK7SAEbCABSxgE7CABSxgBCxgAQsYAQtYwAI2AQsYEDAIGBAwIGAQMCBgQMCAgEHAgIABAQMCBgEDAgYEnE7XPew3" +
  "87AJWMACFjACFrCABWwCFrCABYyABSxgAQvYBCxgAZuABSxgAQsYAQtYwAI2AQtYwAJGwAIWsIARsIAFLGATsIABAYOAAQED" +
  "AgYBAwIGBJwRx7POgQUsYBOwgAUsYAQsYAELWMAmYAEL2AQsYAELWMAIWMACFrAJWMACFjACFrCABSxgE7CABWwCFrCABSxg" +
  "BCxgAQMCBgQMAgYEDAgYEDAIGBAwIODSbc73EueHEzACRsACFrCAEbCABYyAEbCABYyABSxgASNgAQsYASNgAQsYAQtYwAJG" +
  "wAhYwAJGwAIWsIARsIAFDAgYEDAIGBAwIGAQsFsAAgYEDAgYBAwIGBAwIGAQMCBgQMAgYEDAgIABAYOAAQEDAgYEDAIGBAwI" +
  "GAQMCBgQMCBgEDAgYEDAgIBBwICAAQGDgAEBAwIGBAwCBgQMCBgEDAgYEDCw3AersomZxBmpEQAAAABJRU5ErkJggg==";

/** A phone app's sign-in screen, as `device_screenshot` returns it. */
export const phoneShot =
  "iVBORw0KGgoAAAANSUhEUgAAAHgAAADwCAIAAABE5TcwAAABhklEQVR42u3aORXAIBBAQURECmWERUQk0mAiBU3SRAPHMv+t" +
  "gqlYIB3qUkIAGrRAgwYt0KAFelropi6BBg1aoEGDRgAatECDBi3QoAUaNGiBBi3QoEELNGiBBg1aoEELdDzo9z53G9CgQYMG" +
  "DRo0aNCgQYMGDRo0aNCgQYMGDRo0aNCgQYP2Cu67gUCDBi3QoAUaNGiBBg0aAWjQAg0atECD/iul7jagQYMGDRo0aNCgQYNe" +
  "BVqgQYMWaNAC7T7aORo0aNCgQYMGDRo0aNA2Qys4aIEGLdCgQQs0aIEGDVqgQQs0aNACDVqgQYMWaNACDRq0QIMWaNCgBRq0" +
  "BkLn61lxQIMGDRo0aNCgQYMGDRo0aNCgQYMGDRo0aNACDRq0QIMWaNCgBRq0QIMGLdCgBRo0aIEGLdCgQQs0aIEGDVqgQQs0" +
  "aNACDVqgQYMWaNACDRq0QIMWaNCgBRq0QIMGLdCgBRo0aIEGLdCgQQs0aIEGDVqgQQs0aNACDVqgQYMWaNACDTp2H+16OTqI" +
  "nkb1AAAAAElFTkSuQmCC";

/** A web sign-in page, as `ace_browser_screenshot` returns it. */
export const pageShot =
  "iVBORw0KGgoAAAANSUhEUgAAAUAAAADICAIAAAAWZq/8AAACfElEQVR42u3boQ2AMBRF0W6CwaCYgP0YD4frDFWEYGCKNv+H" +
  "83ImKFzXlnlZgaSKIwABAwIGBAwCBgQMCBgQMAgYEDAgYBAwIGBAwICAQcCAgAEBAwIGAQMCBgQMAgYEDAgYEDAIGAgY8HU/" +
  "QFICBgEDAgYEDAIGBAwIGBAwCBgQMCBgEDAgYEDAgIBBwICAAQEDAgYBAwIGBBxd+998dAELWMAIWMACFjACFrCABSxgBCxg" +
  "ASNgAQtYwAhYwAIWsIARsIAFLGAELGABI2AELGABI2ABC1jACFjAAhawgBGwgAUsYAQsYAEjYAELWMACRsACFrCAAQEDAgYE" +
  "DAIGBAwIGAQMCBgQcEDHWRnDzybgLgG/1n8CFrCABSxgBCxgAQvYBCxgAQsYAQtYwAIWsAlYwAI2AQtYwAIWMAIWsIAFbAIW" +
  "sIAFjIAFLGAB4zWS10gCBgQMCBgEDAgYEDAIGBAwIGBAwG5iuYklYNyFdhdawAI2AQtYwAJGwAIWsIAFbAIWsIBNwAIWsIAF" +
  "jIAFLGABm4AFLGABI2ABC1jAAjYBC1jAJmABe43kNZKAAQEDAgYEDAIGBAwIGBAwCBgQcCrTvjGGn03AAhawgBGwgAUsYAQs" +
  "YAELGAELWMACFjACFrCAEbCABSxgASNgAQtYwAhYwAIWMAIWsIAFjIAFLGABI2ABAwIGAQMCBgQMAgYEDAgYEDAIGBAwIGAQ" +
  "sCMAAQMCBgQMAgYEDAgYEDAIGBAwIGAQMCBgQMCAgEHAgIABAQMCBgEDAgYEDAIGBAwIGBAwCBgQMCBgQMAgYEDAgIBBwICA" +
  "AQEDAgYBAwIGBAwCdgogYEDAgIBBwEBsHxo7NXCse0p/AAAAAElFTkSuQmCC";
