/** Definitions only. Nothing in this module starts a CLI or grants recording approval. */
export const ACP_RECORDING_PLAN = [
  {
    agent: "antigravity-acp",
    versions: "reviewed installed server; separate terms/auth resolution",
    scenarios: ["tool-read", "approval-edit", "hidden-child", "surviving-shell", "interrupt"],
  },
  {
    agent: "gemini",
    versions: "0.43.0 or owner-selected newer version",
    scenarios: [
      "tool-read",
      "approval-edit",
      "selectors",
      "http-mcp",
      "load-replay",
      "subagent",
      "subagent-background",
      "surviving-shell",
      "interrupt",
    ],
  },
  {
    agent: "qwen-code",
    versions: "0.0.14",
    scenarios: [
      "tool-read",
      "approval-edit",
      "stdio-mcp",
      "interrupt",
      "unsupported-resume-selectors",
    ],
  },
  {
    agent: "qwen-code",
    versions: "owner-selected modern version",
    scenarios: [
      "tool-read",
      "approval-edit",
      "selectors",
      "mcp-injection",
      "load-list-resume",
      "lifecycle-heartbeat",
      "subagent",
      "subagent-background",
    ],
  },
  {
    agent: "claude-acp",
    versions: "exact bridge and installed native pair",
    scenarios: [
      "tool-read",
      "approval-edit",
      "question",
      "mcp-injection",
      "selectors",
      "resume-fork",
      "negotiated-child",
      "background-shell",
      "interrupt",
      "restart",
    ],
  },
  {
    agent: "codex-acp",
    versions: "exact bridge and installed native pair",
    scenarios: [
      "tool-read",
      "approval-edit",
      "question",
      "mcp-injection",
      "selectors",
      "resume-fork",
      "negotiated-child",
      "background-shell",
      "interrupt",
      "restart",
    ],
  },
  {
    agent: "goose",
    versions: "owner-selected",
    scenarios: [
      "tool-read",
      "approval-edit",
      "mcp-preservation",
      "selectors",
      "load-replay",
      "background-shell",
      "interrupt",
    ],
  },
  {
    agent: "auggie",
    versions: "owner-selected",
    scenarios: [
      "tool-read",
      "approval-edit",
      "mcp-preservation",
      "selectors",
      "load-replay",
      "background-shell",
      "interrupt",
    ],
  },
  {
    agent: "kiro",
    versions: "owner-selected; optional",
    scenarios: [
      "tool-read",
      "approval-edit",
      "mcp-injection",
      "selectors",
      "load-replay",
      "interrupt",
    ],
  },
  {
    agent: "openhands",
    versions: "owner-selected; optional",
    scenarios: [
      "tool-read",
      "approval-edit",
      "mcp-injection",
      "no-op-selectors",
      "load-replay",
      "interrupt",
    ],
  },
] as const;
export const OWNER_RECORDING_MODELS = {
  opencode: "opencode-go/muse-spark-1.3-contributor",
} as const;
