/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as HomeRouteImport } from "./routes/_home"
import { Route as AccountsRouteImport } from "./routes/accounts"
import { Route as ActivityRouteImport } from "./routes/activity"
import { Route as AutomationsRouteImport } from "./routes/automations"
import { Route as DeckRouteImport } from "./routes/deck"
import { Route as MoreRouteImport } from "./routes/more"
import { Route as OffsetsRouteImport } from "./routes/offsets"
import { Route as OffshiftsRouteImport } from "./routes/offshifts"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as SetupRouteImport } from "./routes/setup"
import { Route as SkillsRouteImport } from "./routes/skills"
import { Route as HomeIndexRouteImport } from "./routes/_home.index"
import { Route as HomeArchivedRouteImport } from "./routes/_home.archived"
import { Route as HomeNewRouteImport } from "./routes/_home.new"
import { Route as ActivityIndexRouteImport } from "./routes/activity.index"
import { Route as AutomationsIndexRouteImport } from "./routes/automations.index"
import { Route as AutomationsNewRouteImport } from "./routes/automations.new"
import { Route as DeckSplatRouteImport } from "./routes/deck.$"
import { Route as MoreSplatRouteImport } from "./routes/more.$"
import { Route as OffsetsSplatRouteImport } from "./routes/offsets.$"
import { Route as OffshiftsIndexRouteImport } from "./routes/offshifts.index"
import { Route as OffshiftsRunIdRouteImport } from "./routes/offshifts.$runId"
import { Route as OffshiftsNewRouteImport } from "./routes/offshifts.new"
import { Route as SettingsIndexRouteImport } from "./routes/settings.index"
import { Route as SettingsAdvancedRouteImport } from "./routes/settings.advanced"
import { Route as SettingsAppearanceRouteImport } from "./routes/settings.appearance"
import { Route as SettingsComputerUseRouteImport } from "./routes/settings.computer-use"
import { Route as SettingsGeneralRouteImport } from "./routes/settings.general"
import { Route as SettingsKeyboardRouteImport } from "./routes/settings.keyboard"
import { Route as SettingsNotificationsRouteImport } from "./routes/settings.notifications"
import { Route as SettingsRemoteRouteImport } from "./routes/settings.remote"
import { Route as SettingsThemeEditorRouteImport } from "./routes/settings.theme-editor"
import { Route as SkillsIndexRouteImport } from "./routes/skills.index"
import { Route as SkillsSkillIdRouteImport } from "./routes/skills.$skillId"
import { Route as HomeTThreadIdRouteImport } from "./routes/_home.t.$threadId"
import { Route as AutomationsAutomationIdIndexRouteImport } from "./routes/automations.$automationId.index"
import { Route as AutomationsAutomationIdEditRouteImport } from "./routes/automations.$automationId.edit"
import { Route as SettingsProvidersIndexRouteImport } from "./routes/settings.providers.index"
import { Route as SettingsProvidersProviderRouteImport } from "./routes/settings.providers.$provider"

const HomeRoute = HomeRouteImport.update({
  id: "/_home",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: "/accounts",
  path: "/accounts",
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: "/activity",
  path: "/activity",
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: "/automations",
  path: "/automations",
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: "/deck",
  path: "/deck",
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: "/more",
  path: "/more",
  getParentRoute: () => rootRouteImport,
} as any)
const OffsetsRoute = OffsetsRouteImport.update({
  id: "/offsets",
  path: "/offsets",
  getParentRoute: () => rootRouteImport,
} as any)
const OffshiftsRoute = OffshiftsRouteImport.update({
  id: "/offshifts",
  path: "/offshifts",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: "/skills",
  path: "/skills",
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => HomeRoute,
} as any)
const HomeArchivedRoute = HomeArchivedRouteImport.update({
  id: "/archived",
  path: "/archived",
  getParentRoute: () => HomeRoute,
} as any)
const HomeNewRoute = HomeNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => HomeRoute,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ActivityRoute,
} as any)
const AutomationsIndexRoute = AutomationsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AutomationsRoute,
} as any)
const AutomationsNewRoute = AutomationsNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => AutomationsRoute,
} as any)
const DeckSplatRoute = DeckSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => DeckRoute,
} as any)
const MoreSplatRoute = MoreSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => MoreRoute,
} as any)
const OffsetsSplatRoute = OffsetsSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => OffsetsRoute,
} as any)
const OffshiftsIndexRoute = OffshiftsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => OffshiftsRoute,
} as any)
const OffshiftsRunIdRoute = OffshiftsRunIdRouteImport.update({
  id: "/$runId",
  path: "/$runId",
  getParentRoute: () => OffshiftsRoute,
} as any)
const OffshiftsNewRoute = OffshiftsNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => OffshiftsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: "/advanced",
  path: "/advanced",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: "/appearance",
  path: "/appearance",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsComputerUseRoute = SettingsComputerUseRouteImport.update({
  id: "/computer-use",
  path: "/computer-use",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: "/general",
  path: "/general",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeyboardRoute = SettingsKeyboardRouteImport.update({
  id: "/keyboard",
  path: "/keyboard",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRemoteRoute = SettingsRemoteRouteImport.update({
  id: "/remote",
  path: "/remote",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsThemeEditorRoute = SettingsThemeEditorRouteImport.update({
  id: "/theme-editor",
  path: "/theme-editor",
  getParentRoute: () => SettingsRoute,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SkillsRoute,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: "/$skillId",
  path: "/$skillId",
  getParentRoute: () => SkillsRoute,
} as any)
const HomeTThreadIdRoute = HomeTThreadIdRouteImport.update({
  id: "/t/$threadId",
  path: "/t/$threadId",
  getParentRoute: () => HomeRoute,
} as any)
const AutomationsAutomationIdIndexRoute =
  AutomationsAutomationIdIndexRouteImport.update({
    id: "/$automationId/",
    path: "/$automationId/",
    getParentRoute: () => AutomationsRoute,
  } as any)
const AutomationsAutomationIdEditRoute =
  AutomationsAutomationIdEditRouteImport.update({
    id: "/$automationId/edit",
    path: "/$automationId/edit",
    getParentRoute: () => AutomationsRoute,
  } as any)
const SettingsProvidersIndexRoute = SettingsProvidersIndexRouteImport.update({
  id: "/providers/",
  path: "/providers/",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersProviderRoute =
  SettingsProvidersProviderRouteImport.update({
    id: "/providers/$provider",
    path: "/providers/$provider",
    getParentRoute: () => SettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof HomeIndexRoute
  "/accounts": typeof AccountsRoute
  "/activity": typeof ActivityRouteWithChildren
  "/automations": typeof AutomationsRouteWithChildren
  "/deck": typeof DeckRouteWithChildren
  "/more": typeof MoreRouteWithChildren
  "/offsets": typeof OffsetsRouteWithChildren
  "/offshifts": typeof OffshiftsRouteWithChildren
  "/settings": typeof SettingsRouteWithChildren
  "/setup": typeof SetupRoute
  "/skills": typeof SkillsRouteWithChildren
  "/archived": typeof HomeArchivedRoute
  "/new": typeof HomeNewRoute
  "/automations/new": typeof AutomationsNewRoute
  "/deck/$": typeof DeckSplatRoute
  "/more/$": typeof MoreSplatRoute
  "/offsets/$": typeof OffsetsSplatRoute
  "/offshifts/$runId": typeof OffshiftsRunIdRoute
  "/offshifts/new": typeof OffshiftsNewRoute
  "/settings/advanced": typeof SettingsAdvancedRoute
  "/settings/appearance": typeof SettingsAppearanceRoute
  "/settings/computer-use": typeof SettingsComputerUseRoute
  "/settings/general": typeof SettingsGeneralRoute
  "/settings/keyboard": typeof SettingsKeyboardRoute
  "/settings/notifications": typeof SettingsNotificationsRoute
  "/settings/remote": typeof SettingsRemoteRoute
  "/settings/theme-editor": typeof SettingsThemeEditorRoute
  "/skills/$skillId": typeof SkillsSkillIdRoute
  "/activity/": typeof ActivityIndexRoute
  "/automations/": typeof AutomationsIndexRoute
  "/offshifts/": typeof OffshiftsIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/skills/": typeof SkillsIndexRoute
  "/t/$threadId": typeof HomeTThreadIdRoute
  "/automations/$automationId/edit": typeof AutomationsAutomationIdEditRoute
  "/settings/providers/$provider": typeof SettingsProvidersProviderRoute
  "/automations/$automationId/": typeof AutomationsAutomationIdIndexRoute
  "/settings/providers/": typeof SettingsProvidersIndexRoute
}
export interface FileRoutesByTo {
  "/accounts": typeof AccountsRoute
  "/deck": typeof DeckRouteWithChildren
  "/more": typeof MoreRouteWithChildren
  "/offsets": typeof OffsetsRouteWithChildren
  "/setup": typeof SetupRoute
  "/archived": typeof HomeArchivedRoute
  "/new": typeof HomeNewRoute
  "/automations/new": typeof AutomationsNewRoute
  "/deck/$": typeof DeckSplatRoute
  "/more/$": typeof MoreSplatRoute
  "/offsets/$": typeof OffsetsSplatRoute
  "/offshifts/$runId": typeof OffshiftsRunIdRoute
  "/offshifts/new": typeof OffshiftsNewRoute
  "/settings/advanced": typeof SettingsAdvancedRoute
  "/settings/appearance": typeof SettingsAppearanceRoute
  "/settings/computer-use": typeof SettingsComputerUseRoute
  "/settings/general": typeof SettingsGeneralRoute
  "/settings/keyboard": typeof SettingsKeyboardRoute
  "/settings/notifications": typeof SettingsNotificationsRoute
  "/settings/remote": typeof SettingsRemoteRoute
  "/settings/theme-editor": typeof SettingsThemeEditorRoute
  "/skills/$skillId": typeof SkillsSkillIdRoute
  "/": typeof HomeIndexRoute
  "/activity": typeof ActivityIndexRoute
  "/automations": typeof AutomationsIndexRoute
  "/offshifts": typeof OffshiftsIndexRoute
  "/settings": typeof SettingsIndexRoute
  "/skills": typeof SkillsIndexRoute
  "/t/$threadId": typeof HomeTThreadIdRoute
  "/automations/$automationId/edit": typeof AutomationsAutomationIdEditRoute
  "/settings/providers/$provider": typeof SettingsProvidersProviderRoute
  "/automations/$automationId": typeof AutomationsAutomationIdIndexRoute
  "/settings/providers": typeof SettingsProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_home": typeof HomeRouteWithChildren
  "/accounts": typeof AccountsRoute
  "/activity": typeof ActivityRouteWithChildren
  "/automations": typeof AutomationsRouteWithChildren
  "/deck": typeof DeckRouteWithChildren
  "/more": typeof MoreRouteWithChildren
  "/offsets": typeof OffsetsRouteWithChildren
  "/offshifts": typeof OffshiftsRouteWithChildren
  "/settings": typeof SettingsRouteWithChildren
  "/setup": typeof SetupRoute
  "/skills": typeof SkillsRouteWithChildren
  "/_home/archived": typeof HomeArchivedRoute
  "/_home/new": typeof HomeNewRoute
  "/automations/new": typeof AutomationsNewRoute
  "/deck/$": typeof DeckSplatRoute
  "/more/$": typeof MoreSplatRoute
  "/offsets/$": typeof OffsetsSplatRoute
  "/offshifts/$runId": typeof OffshiftsRunIdRoute
  "/offshifts/new": typeof OffshiftsNewRoute
  "/settings/advanced": typeof SettingsAdvancedRoute
  "/settings/appearance": typeof SettingsAppearanceRoute
  "/settings/computer-use": typeof SettingsComputerUseRoute
  "/settings/general": typeof SettingsGeneralRoute
  "/settings/keyboard": typeof SettingsKeyboardRoute
  "/settings/notifications": typeof SettingsNotificationsRoute
  "/settings/remote": typeof SettingsRemoteRoute
  "/settings/theme-editor": typeof SettingsThemeEditorRoute
  "/skills/$skillId": typeof SkillsSkillIdRoute
  "/_home/": typeof HomeIndexRoute
  "/activity/": typeof ActivityIndexRoute
  "/automations/": typeof AutomationsIndexRoute
  "/offshifts/": typeof OffshiftsIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/skills/": typeof SkillsIndexRoute
  "/_home/t/$threadId": typeof HomeTThreadIdRoute
  "/automations/$automationId/edit": typeof AutomationsAutomationIdEditRoute
  "/settings/providers/$provider": typeof SettingsProvidersProviderRoute
  "/automations/$automationId/": typeof AutomationsAutomationIdIndexRoute
  "/settings/providers/": typeof SettingsProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/accounts"
    | "/activity"
    | "/automations"
    | "/deck"
    | "/more"
    | "/offsets"
    | "/offshifts"
    | "/settings"
    | "/setup"
    | "/skills"
    | "/archived"
    | "/new"
    | "/automations/new"
    | "/deck/$"
    | "/more/$"
    | "/offsets/$"
    | "/offshifts/$runId"
    | "/offshifts/new"
    | "/settings/advanced"
    | "/settings/appearance"
    | "/settings/computer-use"
    | "/settings/general"
    | "/settings/keyboard"
    | "/settings/notifications"
    | "/settings/remote"
    | "/settings/theme-editor"
    | "/skills/$skillId"
    | "/activity/"
    | "/automations/"
    | "/offshifts/"
    | "/settings/"
    | "/skills/"
    | "/t/$threadId"
    | "/automations/$automationId/edit"
    | "/settings/providers/$provider"
    | "/automations/$automationId/"
    | "/settings/providers/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/accounts"
    | "/deck"
    | "/more"
    | "/offsets"
    | "/setup"
    | "/archived"
    | "/new"
    | "/automations/new"
    | "/deck/$"
    | "/more/$"
    | "/offsets/$"
    | "/offshifts/$runId"
    | "/offshifts/new"
    | "/settings/advanced"
    | "/settings/appearance"
    | "/settings/computer-use"
    | "/settings/general"
    | "/settings/keyboard"
    | "/settings/notifications"
    | "/settings/remote"
    | "/settings/theme-editor"
    | "/skills/$skillId"
    | "/"
    | "/activity"
    | "/automations"
    | "/offshifts"
    | "/settings"
    | "/skills"
    | "/t/$threadId"
    | "/automations/$automationId/edit"
    | "/settings/providers/$provider"
    | "/automations/$automationId"
    | "/settings/providers"
  id:
    | "__root__"
    | "/_home"
    | "/accounts"
    | "/activity"
    | "/automations"
    | "/deck"
    | "/more"
    | "/offsets"
    | "/offshifts"
    | "/settings"
    | "/setup"
    | "/skills"
    | "/_home/archived"
    | "/_home/new"
    | "/automations/new"
    | "/deck/$"
    | "/more/$"
    | "/offsets/$"
    | "/offshifts/$runId"
    | "/offshifts/new"
    | "/settings/advanced"
    | "/settings/appearance"
    | "/settings/computer-use"
    | "/settings/general"
    | "/settings/keyboard"
    | "/settings/notifications"
    | "/settings/remote"
    | "/settings/theme-editor"
    | "/skills/$skillId"
    | "/_home/"
    | "/activity/"
    | "/automations/"
    | "/offshifts/"
    | "/settings/"
    | "/skills/"
    | "/_home/t/$threadId"
    | "/automations/$automationId/edit"
    | "/settings/providers/$provider"
    | "/automations/$automationId/"
    | "/settings/providers/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  AccountsRoute: typeof AccountsRoute
  ActivityRoute: typeof ActivityRouteWithChildren
  AutomationsRoute: typeof AutomationsRouteWithChildren
  DeckRoute: typeof DeckRouteWithChildren
  MoreRoute: typeof MoreRouteWithChildren
  OffsetsRoute: typeof OffsetsRouteWithChildren
  OffshiftsRoute: typeof OffshiftsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  SkillsRoute: typeof SkillsRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_home": {
      id: "/_home"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/accounts": {
      id: "/accounts"
      path: "/accounts"
      fullPath: "/accounts"
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/activity": {
      id: "/activity"
      path: "/activity"
      fullPath: "/activity"
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/automations": {
      id: "/automations"
      path: "/automations"
      fullPath: "/automations"
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/deck": {
      id: "/deck"
      path: "/deck"
      fullPath: "/deck"
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/more": {
      id: "/more"
      path: "/more"
      fullPath: "/more"
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/offsets": {
      id: "/offsets"
      path: "/offsets"
      fullPath: "/offsets"
      preLoaderRoute: typeof OffsetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/offshifts": {
      id: "/offshifts"
      path: "/offshifts"
      fullPath: "/offshifts"
      preLoaderRoute: typeof OffshiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/setup": {
      id: "/setup"
      path: "/setup"
      fullPath: "/setup"
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/skills": {
      id: "/skills"
      path: "/skills"
      fullPath: "/skills"
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_home/": {
      id: "/_home/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    "/_home/archived": {
      id: "/_home/archived"
      path: "/archived"
      fullPath: "/archived"
      preLoaderRoute: typeof HomeArchivedRouteImport
      parentRoute: typeof HomeRoute
    }
    "/_home/new": {
      id: "/_home/new"
      path: "/new"
      fullPath: "/new"
      preLoaderRoute: typeof HomeNewRouteImport
      parentRoute: typeof HomeRoute
    }
    "/activity/": {
      id: "/activity/"
      path: "/"
      fullPath: "/activity/"
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof ActivityRoute
    }
    "/automations/": {
      id: "/automations/"
      path: "/"
      fullPath: "/automations/"
      preLoaderRoute: typeof AutomationsIndexRouteImport
      parentRoute: typeof AutomationsRoute
    }
    "/automations/new": {
      id: "/automations/new"
      path: "/new"
      fullPath: "/automations/new"
      preLoaderRoute: typeof AutomationsNewRouteImport
      parentRoute: typeof AutomationsRoute
    }
    "/deck/$": {
      id: "/deck/$"
      path: "/$"
      fullPath: "/deck/$"
      preLoaderRoute: typeof DeckSplatRouteImport
      parentRoute: typeof DeckRoute
    }
    "/more/$": {
      id: "/more/$"
      path: "/$"
      fullPath: "/more/$"
      preLoaderRoute: typeof MoreSplatRouteImport
      parentRoute: typeof MoreRoute
    }
    "/offsets/$": {
      id: "/offsets/$"
      path: "/$"
      fullPath: "/offsets/$"
      preLoaderRoute: typeof OffsetsSplatRouteImport
      parentRoute: typeof OffsetsRoute
    }
    "/offshifts/": {
      id: "/offshifts/"
      path: "/"
      fullPath: "/offshifts/"
      preLoaderRoute: typeof OffshiftsIndexRouteImport
      parentRoute: typeof OffshiftsRoute
    }
    "/offshifts/$runId": {
      id: "/offshifts/$runId"
      path: "/$runId"
      fullPath: "/offshifts/$runId"
      preLoaderRoute: typeof OffshiftsRunIdRouteImport
      parentRoute: typeof OffshiftsRoute
    }
    "/offshifts/new": {
      id: "/offshifts/new"
      path: "/new"
      fullPath: "/offshifts/new"
      preLoaderRoute: typeof OffshiftsNewRouteImport
      parentRoute: typeof OffshiftsRoute
    }
    "/settings/": {
      id: "/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/advanced": {
      id: "/settings/advanced"
      path: "/advanced"
      fullPath: "/settings/advanced"
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/appearance": {
      id: "/settings/appearance"
      path: "/appearance"
      fullPath: "/settings/appearance"
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/computer-use": {
      id: "/settings/computer-use"
      path: "/computer-use"
      fullPath: "/settings/computer-use"
      preLoaderRoute: typeof SettingsComputerUseRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/general": {
      id: "/settings/general"
      path: "/general"
      fullPath: "/settings/general"
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/keyboard": {
      id: "/settings/keyboard"
      path: "/keyboard"
      fullPath: "/settings/keyboard"
      preLoaderRoute: typeof SettingsKeyboardRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/notifications": {
      id: "/settings/notifications"
      path: "/notifications"
      fullPath: "/settings/notifications"
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/remote": {
      id: "/settings/remote"
      path: "/remote"
      fullPath: "/settings/remote"
      preLoaderRoute: typeof SettingsRemoteRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/theme-editor": {
      id: "/settings/theme-editor"
      path: "/theme-editor"
      fullPath: "/settings/theme-editor"
      preLoaderRoute: typeof SettingsThemeEditorRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/skills/": {
      id: "/skills/"
      path: "/"
      fullPath: "/skills/"
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof SkillsRoute
    }
    "/skills/$skillId": {
      id: "/skills/$skillId"
      path: "/$skillId"
      fullPath: "/skills/$skillId"
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof SkillsRoute
    }
    "/_home/t/$threadId": {
      id: "/_home/t/$threadId"
      path: "/t/$threadId"
      fullPath: "/t/$threadId"
      preLoaderRoute: typeof HomeTThreadIdRouteImport
      parentRoute: typeof HomeRoute
    }
    "/automations/$automationId/": {
      id: "/automations/$automationId/"
      path: "/$automationId"
      fullPath: "/automations/$automationId/"
      preLoaderRoute: typeof AutomationsAutomationIdIndexRouteImport
      parentRoute: typeof AutomationsRoute
    }
    "/automations/$automationId/edit": {
      id: "/automations/$automationId/edit"
      path: "/$automationId/edit"
      fullPath: "/automations/$automationId/edit"
      preLoaderRoute: typeof AutomationsAutomationIdEditRouteImport
      parentRoute: typeof AutomationsRoute
    }
    "/settings/providers/": {
      id: "/settings/providers/"
      path: "/providers"
      fullPath: "/settings/providers/"
      preLoaderRoute: typeof SettingsProvidersIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/providers/$provider": {
      id: "/settings/providers/$provider"
      path: "/providers/$provider"
      fullPath: "/settings/providers/$provider"
      preLoaderRoute: typeof SettingsProvidersProviderRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface HomeRouteChildren {
  HomeArchivedRoute: typeof HomeArchivedRoute
  HomeNewRoute: typeof HomeNewRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeTThreadIdRoute: typeof HomeTThreadIdRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeArchivedRoute: HomeArchivedRoute,
  HomeNewRoute: HomeNewRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeTThreadIdRoute: HomeTThreadIdRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface ActivityRouteChildren {
  ActivityIndexRoute: typeof ActivityIndexRoute
}

const ActivityRouteChildren: ActivityRouteChildren = {
  ActivityIndexRoute: ActivityIndexRoute,
}

const ActivityRouteWithChildren = ActivityRoute._addFileChildren(
  ActivityRouteChildren,
)

interface AutomationsRouteChildren {
  AutomationsNewRoute: typeof AutomationsNewRoute
  AutomationsIndexRoute: typeof AutomationsIndexRoute
  AutomationsAutomationIdEditRoute: typeof AutomationsAutomationIdEditRoute
  AutomationsAutomationIdIndexRoute: typeof AutomationsAutomationIdIndexRoute
}

const AutomationsRouteChildren: AutomationsRouteChildren = {
  AutomationsNewRoute: AutomationsNewRoute,
  AutomationsIndexRoute: AutomationsIndexRoute,
  AutomationsAutomationIdEditRoute: AutomationsAutomationIdEditRoute,
  AutomationsAutomationIdIndexRoute: AutomationsAutomationIdIndexRoute,
}

const AutomationsRouteWithChildren = AutomationsRoute._addFileChildren(
  AutomationsRouteChildren,
)

interface DeckRouteChildren {
  DeckSplatRoute: typeof DeckSplatRoute
}

const DeckRouteChildren: DeckRouteChildren = {
  DeckSplatRoute: DeckSplatRoute,
}

const DeckRouteWithChildren = DeckRoute._addFileChildren(DeckRouteChildren)

interface MoreRouteChildren {
  MoreSplatRoute: typeof MoreSplatRoute
}

const MoreRouteChildren: MoreRouteChildren = {
  MoreSplatRoute: MoreSplatRoute,
}

const MoreRouteWithChildren = MoreRoute._addFileChildren(MoreRouteChildren)

interface OffsetsRouteChildren {
  OffsetsSplatRoute: typeof OffsetsSplatRoute
}

const OffsetsRouteChildren: OffsetsRouteChildren = {
  OffsetsSplatRoute: OffsetsSplatRoute,
}

const OffsetsRouteWithChildren =
  OffsetsRoute._addFileChildren(OffsetsRouteChildren)

interface OffshiftsRouteChildren {
  OffshiftsRunIdRoute: typeof OffshiftsRunIdRoute
  OffshiftsNewRoute: typeof OffshiftsNewRoute
  OffshiftsIndexRoute: typeof OffshiftsIndexRoute
}

const OffshiftsRouteChildren: OffshiftsRouteChildren = {
  OffshiftsRunIdRoute: OffshiftsRunIdRoute,
  OffshiftsNewRoute: OffshiftsNewRoute,
  OffshiftsIndexRoute: OffshiftsIndexRoute,
}

const OffshiftsRouteWithChildren = OffshiftsRoute._addFileChildren(
  OffshiftsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsComputerUseRoute: typeof SettingsComputerUseRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsKeyboardRoute: typeof SettingsKeyboardRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsRemoteRoute: typeof SettingsRemoteRoute
  SettingsThemeEditorRoute: typeof SettingsThemeEditorRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsProvidersProviderRoute: typeof SettingsProvidersProviderRoute
  SettingsProvidersIndexRoute: typeof SettingsProvidersIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsComputerUseRoute: SettingsComputerUseRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsKeyboardRoute: SettingsKeyboardRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsRemoteRoute: SettingsRemoteRoute,
  SettingsThemeEditorRoute: SettingsThemeEditorRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsProvidersProviderRoute: SettingsProvidersProviderRoute,
  SettingsProvidersIndexRoute: SettingsProvidersIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SkillsRouteChildren {
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsSkillIdRoute: SkillsSkillIdRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  AccountsRoute: AccountsRoute,
  ActivityRoute: ActivityRouteWithChildren,
  AutomationsRoute: AutomationsRouteWithChildren,
  DeckRoute: DeckRouteWithChildren,
  MoreRoute: MoreRouteWithChildren,
  OffsetsRoute: OffsetsRouteWithChildren,
  OffshiftsRoute: OffshiftsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  SkillsRoute: SkillsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
