/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsModelsRouteImport } from './routes/settings.models'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsEditorRouteImport } from './routes/settings.editor'
import { Route as SettingsChatRouteImport } from './routes/settings.chat'
import { Route as SettingsBrowserRouteImport } from './routes/settings.browser'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAdvancedRouteImport } from './routes/settings.advanced'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEditorRoute = SettingsEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsChatRoute = SettingsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBrowserRoute = SettingsBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/_chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/$threadId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/archived'
    | '/settings/browser'
    | '/settings/chat'
    | '/settings/editor'
    | '/settings/general'
    | '/settings/models'
    | '/settings/providers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/$threadId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/archived'
    | '/settings/browser'
    | '/settings/chat'
    | '/settings/editor'
    | '/settings/general'
    | '/settings/models'
    | '/settings/providers'
    | '/'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/_chat/$threadId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/archived'
    | '/settings/browser'
    | '/settings/chat'
    | '/settings/editor'
    | '/settings/general'
    | '/settings/models'
    | '/settings/providers'
    | '/_chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/editor': {
      id: '/settings/editor'
      path: '/editor'
      fullPath: '/settings/editor'
      preLoaderRoute: typeof SettingsEditorRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/chat': {
      id: '/settings/chat'
      path: '/chat'
      fullPath: '/settings/chat'
      preLoaderRoute: typeof SettingsChatRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/browser': {
      id: '/settings/browser'
      path: '/browser'
      fullPath: '/settings/browser'
      preLoaderRoute: typeof SettingsBrowserRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsBrowserRoute: typeof SettingsBrowserRoute
  SettingsChatRoute: typeof SettingsChatRoute
  SettingsEditorRoute: typeof SettingsEditorRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsBrowserRoute: SettingsBrowserRoute,
  SettingsChatRoute: SettingsChatRoute,
  SettingsEditorRoute: SettingsEditorRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
