/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalsRouteImport } from './routes/terminals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsModelsRouteImport } from './routes/settings.models'
import { Route as SettingsKeyboardShortcutsRouteImport } from './routes/settings.keyboard-shortcuts'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsEnvironmentRouteImport } from './routes/settings.environment'
import { Route as SettingsEditorRouteImport } from './routes/settings.editor'
import { Route as SettingsDevicesRouteImport } from './routes/settings.devices'
import { Route as SettingsChatRouteImport } from './routes/settings.chat'
import { Route as SettingsBrowserRouteImport } from './routes/settings.browser'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAdvancedRouteImport } from './routes/settings.advanced'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as SettingsProjectEnvironmentProjectIdRouteImport } from './routes/settings.project-environment.$projectId'

const TerminalsRoute = TerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeyboardShortcutsRoute =
  SettingsKeyboardShortcutsRouteImport.update({
    id: '/keyboard-shortcuts',
    path: '/keyboard-shortcuts',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEnvironmentRoute = SettingsEnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEditorRoute = SettingsEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDevicesRoute = SettingsDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsChatRoute = SettingsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBrowserRoute = SettingsBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsProjectEnvironmentProjectIdRoute =
  SettingsProjectEnvironmentProjectIdRouteImport.update({
    id: '/project-environment/$projectId',
    path: '/project-environment/$projectId',
    getParentRoute: () => SettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/terminals': typeof TerminalsRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/environment': typeof SettingsEnvironmentRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keyboard-shortcuts': typeof SettingsKeyboardShortcutsRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/project-environment/$projectId': typeof SettingsProjectEnvironmentProjectIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteWithChildren
  '/terminals': typeof TerminalsRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/environment': typeof SettingsEnvironmentRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keyboard-shortcuts': typeof SettingsKeyboardShortcutsRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/': typeof ChatIndexRoute
  '/settings/project-environment/$projectId': typeof SettingsProjectEnvironmentProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/terminals': typeof TerminalsRoute
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/environment': typeof SettingsEnvironmentRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keyboard-shortcuts': typeof SettingsKeyboardShortcutsRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/_chat/': typeof ChatIndexRoute
  '/settings/project-environment/$projectId': typeof SettingsProjectEnvironmentProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/terminals'
    | '/$threadId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/browser'
    | '/settings/chat'
    | '/settings/devices'
    | '/settings/editor'
    | '/settings/environment'
    | '/settings/general'
    | '/settings/keyboard-shortcuts'
    | '/settings/models'
    | '/settings/providers'
    | '/settings/project-environment/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/terminals'
    | '/$threadId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/browser'
    | '/settings/chat'
    | '/settings/devices'
    | '/settings/editor'
    | '/settings/environment'
    | '/settings/general'
    | '/settings/keyboard-shortcuts'
    | '/settings/models'
    | '/settings/providers'
    | '/'
    | '/settings/project-environment/$projectId'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/terminals'
    | '/_chat/$threadId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/browser'
    | '/settings/chat'
    | '/settings/devices'
    | '/settings/editor'
    | '/settings/environment'
    | '/settings/general'
    | '/settings/keyboard-shortcuts'
    | '/settings/models'
    | '/settings/providers'
    | '/_chat/'
    | '/settings/project-environment/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  TerminalsRoute: typeof TerminalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminals': {
      id: '/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof TerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keyboard-shortcuts': {
      id: '/settings/keyboard-shortcuts'
      path: '/keyboard-shortcuts'
      fullPath: '/settings/keyboard-shortcuts'
      preLoaderRoute: typeof SettingsKeyboardShortcutsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/environment': {
      id: '/settings/environment'
      path: '/environment'
      fullPath: '/settings/environment'
      preLoaderRoute: typeof SettingsEnvironmentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/editor': {
      id: '/settings/editor'
      path: '/editor'
      fullPath: '/settings/editor'
      preLoaderRoute: typeof SettingsEditorRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/devices': {
      id: '/settings/devices'
      path: '/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof SettingsDevicesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/chat': {
      id: '/settings/chat'
      path: '/chat'
      fullPath: '/settings/chat'
      preLoaderRoute: typeof SettingsChatRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/browser': {
      id: '/settings/browser'
      path: '/browser'
      fullPath: '/settings/browser'
      preLoaderRoute: typeof SettingsBrowserRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/project-environment/$projectId': {
      id: '/settings/project-environment/$projectId'
      path: '/project-environment/$projectId'
      fullPath: '/settings/project-environment/$projectId'
      preLoaderRoute: typeof SettingsProjectEnvironmentProjectIdRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsBrowserRoute: typeof SettingsBrowserRoute
  SettingsChatRoute: typeof SettingsChatRoute
  SettingsDevicesRoute: typeof SettingsDevicesRoute
  SettingsEditorRoute: typeof SettingsEditorRoute
  SettingsEnvironmentRoute: typeof SettingsEnvironmentRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsKeyboardShortcutsRoute: typeof SettingsKeyboardShortcutsRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsProjectEnvironmentProjectIdRoute: typeof SettingsProjectEnvironmentProjectIdRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsBrowserRoute: SettingsBrowserRoute,
  SettingsChatRoute: SettingsChatRoute,
  SettingsDevicesRoute: SettingsDevicesRoute,
  SettingsEditorRoute: SettingsEditorRoute,
  SettingsEnvironmentRoute: SettingsEnvironmentRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsKeyboardShortcutsRoute: SettingsKeyboardShortcutsRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsProjectEnvironmentProjectIdRoute:
    SettingsProjectEnvironmentProjectIdRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  TerminalsRoute: TerminalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
