// Keep this list intentionally short and clean: it reads better,
// avoids duplicates, and prevents flickery “slot machine” vibes.
export const LOADING_WORDS = [
  "Assessing",
  "Bootstrapping",
  "Calibrating",
  "Checking",
  "Compiling",
  "Connecting",
  "Decrypting",
  "Indexing",
  "Initializing",
  "Loading",
  "Optimizing",
  "Preparing",
  "Provisioning",
  "Resolving",
  "Routing",
  "Scanning",
  "Securing",
  "Setting up",
  "Starting",
  "Synchronizing",
  "Validating",
  "Verifying",
  "Warming up",
] as const;
