import type { ProviderIntegrationCapabilities, ProviderKind } from "@ace/contracts";

import type { ProviderAdapterCapabilities } from "./Services/ProviderAdapter.ts";

const PROVIDER_INTEGRATION_CAPABILITIES: Record<ProviderKind, ProviderIntegrationCapabilities> = {
  codex: {
    sessionModelSwitch: "in-session",
    sessionModelOptionsSwitch: "in-session",
    liveTurnDiffMode: "native",
    reviewChangesMode: "provider",
    reviewSurface: "turn-native",
    approvalRequestsMode: "native",
    turnSteeringMode: "native",
    transcriptAuthority: "provider",
    historyAuthority: "provider-session",
    sessionResumeMode: "native",
    sessionForkMode: "native",
    sideConversationMode: "native-fork",
    sideConversationCommands: [".side"],
    providerThreadTargetingMode: "native",
    goalControlMode: "native",
    multiAgentMode: "native",
    multiAgentInvocationPrefixes: [],
    multiAgentDefinitionPaths: [],
    hookMode: "native",
    extensionMode: "native",
    mcpMode: "native",
    remoteAgentMode: "native",
    webAccessMode: "native",
    hostedSessionMode: "native",
  },
  claudeAgent: {
    sessionModelSwitch: "in-session",
    sessionModelOptionsSwitch: "restart-session",
    liveTurnDiffMode: "reconstructed",
    reviewChangesMode: "provider",
    reviewSurface: "git-worktree",
    approvalRequestsMode: "native",
    turnSteeringMode: "queued-message",
    transcriptAuthority: "provider",
    historyAuthority: "provider-session",
    sessionResumeMode: "native",
    sessionForkMode: "native",
    sideConversationMode: "native-fork",
    sideConversationCommands: ["/btw"],
    providerThreadTargetingMode: "unsupported",
    goalControlMode: "unsupported",
    multiAgentMode: "native",
    multiAgentInvocationPrefixes: [],
    multiAgentDefinitionPaths: [".claude/agents", "~/.claude/agents"],
    hookMode: "native",
    extensionMode: "native",
    mcpMode: "native",
    remoteAgentMode: "unsupported",
    webAccessMode: "native",
    hostedSessionMode: "native",
  },
  gemini: {
    sessionModelSwitch: "in-session",
    sessionModelOptionsSwitch: "in-session",
    liveTurnDiffMode: "reconstructed",
    reviewChangesMode: "provider",
    reviewSurface: "editor-native",
    approvalRequestsMode: "native",
    turnSteeringMode: "queued-message",
    transcriptAuthority: "local",
    historyAuthority: "project-local",
    sessionResumeMode: "local-replay",
    sessionForkMode: "local-replay",
    sideConversationMode: "replay-fork",
    sideConversationCommands: [],
    providerThreadTargetingMode: "unsupported",
    goalControlMode: "unsupported",
    multiAgentMode: "native",
    multiAgentInvocationPrefixes: [],
    multiAgentDefinitionPaths: [".gemini/agents", "~/.gemini/agents"],
    hookMode: "native",
    extensionMode: "native",
    mcpMode: "native",
    remoteAgentMode: "native",
    webAccessMode: "native",
    hostedSessionMode: "unsupported",
  },
  cursor: {
    sessionModelSwitch: "restart-session",
    sessionModelOptionsSwitch: "restart-session",
    liveTurnDiffMode: "workspace",
    reviewChangesMode: "git",
    reviewSurface: "pending-changes",
    approvalRequestsMode: "native",
    turnSteeringMode: "queued-message",
    transcriptAuthority: "local",
    historyAuthority: "project-local",
    sessionResumeMode: "local-replay",
    sessionForkMode: "local-replay",
    sideConversationMode: "replay-fork",
    sideConversationCommands: [],
    providerThreadTargetingMode: "unsupported",
    goalControlMode: "unsupported",
    multiAgentMode: "agent-command",
    multiAgentInvocationPrefixes: [],
    multiAgentDefinitionPaths: [".cursor/agents/*.md", "~/.cursor/agents/*.md"],
    hookMode: "unsupported",
    extensionMode: "local-discovery",
    mcpMode: "native",
    remoteAgentMode: "unsupported",
    webAccessMode: "native",
    hostedSessionMode: "native",
  },
  pi: {
    sessionModelSwitch: "in-session",
    sessionModelOptionsSwitch: "in-session",
    liveTurnDiffMode: "workspace",
    reviewChangesMode: "git",
    reviewSurface: "git-worktree",
    approvalRequestsMode: "none",
    turnSteeringMode: "native",
    transcriptAuthority: "local",
    historyAuthority: "local-server-session",
    sessionResumeMode: "local-replay",
    sessionForkMode: "local-replay",
    sideConversationMode: "replay-fork",
    sideConversationCommands: [],
    providerThreadTargetingMode: "unsupported",
    goalControlMode: "unsupported",
    multiAgentMode: "agent-command",
    multiAgentInvocationPrefixes: [],
    multiAgentDefinitionPaths: [],
    hookMode: "unsupported",
    extensionMode: "native",
    mcpMode: "unsupported",
    remoteAgentMode: "unsupported",
    webAccessMode: "unsupported",
    hostedSessionMode: "unsupported",
  },
  githubCopilot: {
    sessionModelSwitch: "restart-session",
    sessionModelOptionsSwitch: "restart-session",
    liveTurnDiffMode: "workspace",
    reviewChangesMode: "git",
    reviewSurface: "editor-native",
    approvalRequestsMode: "native",
    turnSteeringMode: "queued-message",
    transcriptAuthority: "local",
    historyAuthority: "local-server-session",
    sessionResumeMode: "native",
    sessionForkMode: "local-replay",
    sideConversationMode: "replay-fork",
    sideConversationCommands: [],
    providerThreadTargetingMode: "unsupported",
    goalControlMode: "unsupported",
    multiAgentMode: "native",
    multiAgentInvocationPrefixes: ["/agent"],
    multiAgentDefinitionPaths: [".github/agents/*.agent.md", "~/.copilot/agents/*.agent.md"],
    hookMode: "native",
    extensionMode: "native",
    mcpMode: "native",
    remoteAgentMode: "native",
    webAccessMode: "agent-command",
    hostedSessionMode: "native",
  },
  opencode: {
    sessionModelSwitch: "in-session",
    sessionModelOptionsSwitch: "in-session",
    liveTurnDiffMode: "workspace",
    reviewChangesMode: "git",
    reviewSurface: "git-worktree",
    approvalRequestsMode: "native",
    turnSteeringMode: "queued-message",
    transcriptAuthority: "local",
    historyAuthority: "local-server-session",
    sessionResumeMode: "local-replay",
    sessionForkMode: "local-replay",
    sideConversationMode: "replay-fork",
    sideConversationCommands: [],
    providerThreadTargetingMode: "native",
    goalControlMode: "unsupported",
    multiAgentMode: "native",
    multiAgentInvocationPrefixes: ["@"],
    multiAgentDefinitionPaths: [
      "opencode.json agent",
      "~/.config/opencode/opencode.json agent",
      ".opencode/agents",
      "~/.config/opencode/agents",
    ],
    hookMode: "native",
    extensionMode: "native",
    mcpMode: "native",
    remoteAgentMode: "unsupported",
    webAccessMode: "mcp-or-shell",
    hostedSessionMode: "unsupported",
  },
};

export function defaultProviderIntegrationCapabilities(
  provider: ProviderKind,
): ProviderIntegrationCapabilities {
  return PROVIDER_INTEGRATION_CAPABILITIES[provider];
}

export function resolveProviderIntegrationCapabilities(
  provider: ProviderKind,
  capabilities?: ProviderAdapterCapabilities | ProviderIntegrationCapabilities | null,
): ProviderIntegrationCapabilities {
  const defaults = defaultProviderIntegrationCapabilities(provider);
  if (!capabilities) {
    return defaults;
  }
  return {
    ...defaults,
    ...capabilities,
    sessionModelSwitch: capabilities.sessionModelSwitch ?? defaults.sessionModelSwitch,
    sessionModelOptionsSwitch:
      capabilities.sessionModelOptionsSwitch ?? defaults.sessionModelOptionsSwitch,
    sideConversationCommands:
      capabilities.sideConversationCommands ?? defaults.sideConversationCommands,
    multiAgentInvocationPrefixes:
      capabilities.multiAgentInvocationPrefixes ?? defaults.multiAgentInvocationPrefixes,
    multiAgentDefinitionPaths:
      capabilities.multiAgentDefinitionPaths ?? defaults.multiAgentDefinitionPaths,
  };
}
