// Generated by scripts/provider-icons.ts from @lobehub/icons-static-svg 1.95.1
// (icons/antigravity.svg, MIT, Copyright (c) 2023 LobeHub; see NOTICE). Do not edit.
import type { BrandArt } from "../brand-art-types.ts";

export const art: BrandArt = {"viewBox":"-0.5 -0.5 25 25","mono":[{"d":"M21.751 22.607c1.34 1.005 3.35.335 1.508-1.508C17.73 15.74 18.904 1 12.037 1 5.17 1 6.342 15.74.815 21.1c-2.01 2.009.167 2.511 1.507 1.506 5.192-3.517 4.857-9.714 9.715-9.714 4.857 0 4.522 6.197 9.714 9.715z","fillRule":"evenodd"}]};
