// Generated by scripts/provider-icons.ts from @lobehub/icons-static-svg 1.95.1
// (icons/geminicli.svg, MIT, Copyright (c) 2023 LobeHub; see NOTICE). Do not edit.
import type { BrandArt } from "../brand-art-types.ts";

export const art: BrandArt = {"viewBox":"0 0 24 24","mono":[{"d":"M16.793 10.358v3.867L7.236 18.82v-2.8l7.751-3.728-7.75-3.728V5.763l9.556 4.595z","fillRule":"evenodd"},{"d":"M19.608 0A4.392 4.392 0 0124 4.392v15.216A4.392 4.392 0 0119.608 24H4.392A4.392 4.392 0 010 19.608V4.392A4.392 4.392 0 014.392 0h15.216zM4.26 1.444A2.816 2.816 0 001.444 4.26v15.48a2.816 2.816 0 002.816 2.816h15.48a2.816 2.816 0 002.816-2.816V4.26a2.816 2.816 0 00-2.816-2.816H4.26z","fillRule":"evenodd","clipRule":"evenodd"}]};
