// Generated by scripts/provider-icons.ts from @lobehub/icons-static-svg 1.95.1 (icons/*.svg)
// and scripts/brand-marks/ (each owner's brand kit); see NOTICE. Do not edit.
import type { BrandArt } from "../brand-art-types.ts";

/** Every brand ace has a mark for. */
export type Brand = "amp" | "antigravity" | "claude" | "cline" | "codebuddy" | "cursor" | "deepseek" | "devin" | "gemini" | "geminicli" | "gemma" | "githubcopilot" | "goose" | "grok" | "junie" | "kilocode" | "kimi" | "langchain" | "meta" | "minimax" | "mistral" | "openai" | "opencode" | "openrouter" | "pi" | "qoder" | "qwen" | "snowflake" | "zai";

/** Loads one brand's mark; each is its own chunk. */
export const brandArt: Record<Brand, () => Promise<BrandArt>> = {
  amp: () => import("./amp.gen.ts").then((m) => m.art),
  antigravity: () => import("./antigravity.gen.ts").then((m) => m.art),
  claude: () => import("./claude.gen.ts").then((m) => m.art),
  cline: () => import("./cline.gen.ts").then((m) => m.art),
  codebuddy: () => import("./codebuddy.gen.ts").then((m) => m.art),
  cursor: () => import("./cursor.gen.ts").then((m) => m.art),
  deepseek: () => import("./deepseek.gen.ts").then((m) => m.art),
  devin: () => import("./devin.gen.ts").then((m) => m.art),
  gemini: () => import("./gemini.gen.ts").then((m) => m.art),
  geminicli: () => import("./geminicli.gen.ts").then((m) => m.art),
  gemma: () => import("./gemma.gen.ts").then((m) => m.art),
  githubcopilot: () => import("./githubcopilot.gen.ts").then((m) => m.art),
  goose: () => import("./goose.gen.ts").then((m) => m.art),
  grok: () => import("./grok.gen.ts").then((m) => m.art),
  junie: () => import("./junie.gen.ts").then((m) => m.art),
  kilocode: () => import("./kilocode.gen.ts").then((m) => m.art),
  kimi: () => import("./kimi.gen.ts").then((m) => m.art),
  langchain: () => import("./langchain.gen.ts").then((m) => m.art),
  meta: () => import("./meta.gen.ts").then((m) => m.art),
  minimax: () => import("./minimax.gen.ts").then((m) => m.art),
  mistral: () => import("./mistral.gen.ts").then((m) => m.art),
  openai: () => import("./openai.gen.ts").then((m) => m.art),
  opencode: () => import("./opencode.gen.ts").then((m) => m.art),
  openrouter: () => import("./openrouter.gen.ts").then((m) => m.art),
  pi: () => import("./pi.gen.ts").then((m) => m.art),
  qoder: () => import("./qoder.gen.ts").then((m) => m.art),
  qwen: () => import("./qwen.gen.ts").then((m) => m.art),
  snowflake: () => import("./snowflake.gen.ts").then((m) => m.art),
  zai: () => import("./zai.gen.ts").then((m) => m.art),
};
