// Generated by scripts/provider-icons.ts from @lobehub/icons-static-svg 1.95.1
// (icons/opencode.svg, MIT, Copyright (c) 2023 LobeHub; see NOTICE). Do not edit.
import type { BrandArt } from "../brand-art-types.ts";

export const art: BrandArt = {"viewBox":"0 0 24 24","mono":[{"d":"M16 6H8v12h8V6zm4 16H4V2h16v20z","fillRule":"evenodd"}]};
