// Generated by scripts/provider-icons.ts from @lobehub/icons-static-svg 1.95.1
// (icons/openrouter.svg, MIT, Copyright (c) 2023 LobeHub; see NOTICE). Do not edit.
import type { BrandArt } from "../brand-art-types.ts";

export const art: BrandArt = {"viewBox":"-0.5 -0.5 25 25","mono":[{"d":"M18.654 3.87a5.087 5.087 0 110 10.174L23.7 19.09c.64.641.187 1.737-.72 1.737H8.48a8.479 8.479 0 010-16.958h10.175zM8.479 7.26a5.087 5.087 0 100 10.176 5.087 5.087 0 000-10.175z","fillRule":"evenodd"}]};
