// Generated by scripts/provider-icons.ts from OpenCode's brand assets https://opencode.ai/brand (packages/ui/src/assets/favicon/favicon-v3.svg).
// The mark is its owner's trademark; see NOTICE. Do not edit.
import type { BrandArt } from "../brand-art-types.ts";

export const art: BrandArt = {"viewBox":"128 96 256 320","mono":[{"d":"M320 224V352H192V224H320Z","opacity":0.35},{"d":"M384 416H128V96H384V416ZM320 160H192V352H320V160Z","fillRule":"evenodd","clipRule":"evenodd"}]};
