// Generated by scripts/provider-icons.ts from @lobehub/icons-static-svg 1.95.1
// (icons/pi.svg, MIT, Copyright (c) 2023 LobeHub; see NOTICE). Do not edit.
import type { BrandArt } from "../brand-art-types.ts";

export const art: BrandArt = {"viewBox":"-0.5 -0.5 25 25","mono":[{"d":"M1 1h16.5v11H12v5.5H6.5V23H1V1zm5.5 5.5V12H12V6.5H6.5z","fillRule":"evenodd","clipRule":"evenodd"},{"d":"M17.5 12H23v11h-5.5V12z","fillRule":"evenodd"}]};
