// Generated by scripts/provider-icons.ts from @lobehub/icons-static-svg 1.95.1
// (icons/zai.svg, MIT, Copyright (c) 2023 LobeHub; see NOTICE). Do not edit.
import type { BrandArt } from "../brand-art-types.ts";

export const art: BrandArt = {"viewBox":"0 0 24 24","mono":[{"d":"M12.105 2L9.927 4.953H.653L2.83 2h9.276zM23.254 19.048L21.078 22h-9.242l2.174-2.952h9.244zM24 2L9.264 22H0L14.736 2H24z","fillRule":"evenodd"}]};
