import { afterEach, expect, test } from "vitest";
import { join } from "node:path";
import { mkdir, readFile } from "node:fs/promises";
import { DatabaseSync } from "node:sqlite";
import { object } from "@ace/native-session";
import { sanitizeUserText } from "./index.ts";
import {
  environment,
  jsonl,
  claudeRecords,
  codexRecords,
  nativeId,
  otherId,
  cwd,
  init,
  memorySink,
  text,
} from "./test-support.ts";

const cleanup: (() => Promise<void>)[] = [];
afterEach(async () => {
  for (const close of cleanup.splice(0)) await close();
});
const plugins =
  "<recommended_plugins>\nAvailable plugins\n- Example (app-example)\n</recommended_plugins>";
const caveat =
  "<local-command-caveat>Generated by a local command</local-command-caveat>\n<command-name>/clear</command-name><command-message>clear</command-message><command-args></command-args>";

test.each([
  [plugins + "\nFix reconnect retries", "Fix reconnect retries"],
  [caveat + "\nCheck replay order", "Check replay order"],
  [
    "<environment_context><cwd>/scratch</cwd></environment_context><user_instructions>Rules</user_instructions>\nAdd search",
    "Add search",
  ],
  [
    "# AGENTS.md instructions for /scratch\n<INSTRUCTIONS>private context</INSTRUCTIONS>\n<environment_context>context</environment_context>\nBuild a picker",
    "Build a picker",
  ],
  [
    "<command-name>/review</command-name><command-message>review</command-message><command-args>Check the new dialog</command-args>",
    "Check the new dialog",
  ],
  ["/review Check the dialog [Image 1]", "Check the dialog"],
  ["<recommended_plugins>cut off raw XML", ""],
  [plugins + "\n" + caveat, ""],
])("Saved prompt envelopes are removed before displaying %s", (raw, expected) => {
  expect(sanitizeUserText(raw)).toBe(expected);
});

test("Claude summaries take priority, context-only and sidechain sessions stay hidden, and imported prompts are cleaned", async () => {
  const env = await environment();
  cleanup.push(env.close);
  const home = join(env.root, "claude");
  const path = join(home, "projects/p", nativeId + ".jsonl");
  await jsonl(path, [
    ...claudeRecords(plugins + "\n" + caveat + "\nFix reconnect retries"),
    { type: "summary", summary: "Repair reconnect backoff" },
  ]);
  await jsonl(
    join(home, "projects/p/noise.jsonl"),
    claudeRecords(plugins + "\n" + caveat, "noise"),
  );
  await jsonl(
    join(home, "projects/p/sidechain.jsonl"),
    claudeRecords("Background review", "sidechain").map((r) =>
      Object.assign({}, r, { isSidechain: true }),
    ),
  );
  await jsonl(join(home, "projects/p/untitled.jsonl"), [
    ...claudeRecords("Check replay order", "untitled"),
    { type: "ai-title", aiTitle: "Untitled session" },
  ]);
  const before = await readFile(path);
  const service = await env.start([{ id: "claude", provider: "claude", homeDir: home }]);
  await service.scan();
  const sessions = (await service.list({ type: "history.list", cwd })).sessions;
  expect(sessions.map((s) => s.title).toSorted()).toEqual([
    "Check replay order",
    "Repair reconnect backoff",
  ]);
  const root = sessions.find((s) => s.nativeId === nativeId);
  if (!root) throw new Error("Missing root");
  const sink = memorySink();
  await service.importSession(init(root.id), sink);
  expect(text(sink.items)).toBe("Fix reconnect retries answer");
  expect(await readFile(path)).toEqual(before);
});

test("A captionless user attachment gets a date title instead of an ID or raw tags", async () => {
  const env = await environment();
  cleanup.push(env.close);
  const home = join(env.root, "claude");
  await jsonl(join(home, "projects/p", nativeId + ".jsonl"), [
    {
      type: "user",
      sessionId: nativeId,
      cwd,
      message: {
        role: "user",
        content: [
          { type: "image", source: { type: "base64", media_type: "image/png", data: "fixture" } },
        ],
      },
    },
  ]);
  const service = await env.start([{ id: "claude", provider: "claude", homeDir: home }]);
  await service.scan();
  const root = (await service.list({ type: "history.list", cwd })).sessions[0];
  expect(root?.title).toMatch(/^Session from \d{4}-\d{2}-\d{2}$/);
});

test("Paginated Codex rollouts import real prompts, use index names, hide exec and subagents, and search older titles", async () => {
  const env = await environment();
  cleanup.push(env.close);
  const home = join(env.root, "codex");
  const records = codexRecords();
  const first = object(records[0]);
  await jsonl(join(home, "sessions/rollout.jsonl"), [
    { ...first, payload: { id: nativeId, cwd, history_mode: "paginated", source: "vscode" } },
    ...records.slice(1).map((value) => {
      const r = object(value),
        p = object(r.payload);
      return r.type === "response_item" && p.type === "message" && p.role === "user"
        ? Object.assign({}, r, {
            payload: Object.assign({}, p, {
              content: [{ type: "input_text", text: plugins + "\nFix the retry loop" }],
            }),
          })
        : r;
    }),
  ]);
  await jsonl(join(home, "sessions/exec.jsonl"), [
    { type: "session_meta", payload: { id: otherId, cwd, source: "exec" } },
    ...records.slice(1),
  ]);
  await jsonl(join(home, "sessions/subagent.jsonl"), [
    {
      type: "session_meta",
      payload: {
        id: "00000000-0000-0000-0000-000000000003",
        cwd,
        source: { subagent: { other: "guardian" } },
      },
    },
    ...records.slice(1),
  ]);
  await jsonl(join(home, "session_index.jsonl"), [
    { id: nativeId, thread_name: "Retry loop audit", updated_at: "2026-10-08T12:00:00Z" },
  ]);
  const statePath = join(home, "state_5.sqlite");
  const state = new DatabaseSync(statePath);
  state.exec("CREATE TABLE threads(id TEXT,cwd TEXT,title TEXT,updated_at INTEGER)");
  state.prepare("INSERT INTO threads VALUES(?,?,?,?)").run(nativeId, cwd, "State title", 1);
  state.close();
  const service = await env.start([{ id: "codex", provider: "codex", homeDir: home }]);
  await service.scan();
  const sessions = (await service.list({ type: "history.list", cwd, openableOnly: true })).sessions;
  expect(sessions.map((s) => s.title)).toEqual(["Retry loop audit"]);
  const root = sessions[0];
  if (!root) throw new Error("Missing session");
  const sink = memorySink();
  await service.importSession(init(root.id), sink);
  expect(text(sink.items)).toBe("Fix the retry loop codex answer");
  expect(sink.thread?.title).toBe("Retry loop audit");
  expect(
    (await service.list({ type: "history.list", cwd, search: "AUDIT" })).sessions,
  ).toHaveLength(1);
  expect((await service.list({ type: "history.list", cwd, search: "missing" })).sessions).toEqual(
    [],
  );
  const changedState = new DatabaseSync(statePath);
  changedState.prepare("UPDATE threads SET title=?").run("Changed state title");
  changedState.close();
  await service.scan();
  expect((await service.list({ type: "history.list", cwd })).sessions[0]?.title).toBe(
    "Retry loop audit",
  );
  await jsonl(join(home, "session_index.jsonl"), [
    { id: nativeId, thread_name: "Renamed retry audit" },
  ]);
  await service.scan();
  expect((await service.list({ type: "history.list", cwd })).sessions[0]?.title).toBe(
    "Renamed retry audit",
  );
});

test.each(["coexisting", "v2 only"])(
  "OpenCode %s imports ordered user text, reasoning and completed tool results without duplicate legacy messages",
  async (storage) => {
    const env = await environment();
    cleanup.push(env.close);
    const home = join(env.root, "opencode");
    await mkdir(home);
    const path = join(home, "opencode.db");
    const db = new DatabaseSync(path);
    db.exec(`CREATE TABLE session(id TEXT PRIMARY KEY,directory TEXT,title TEXT,time_updated INTEGER,parent_id TEXT);
    CREATE TABLE message(id TEXT PRIMARY KEY,session_id TEXT,time_created INTEGER,data TEXT);
    CREATE TABLE part(id TEXT PRIMARY KEY,message_id TEXT,data TEXT);
    CREATE TABLE session_message(id TEXT PRIMARY KEY,session_id TEXT,type TEXT,seq INTEGER,data TEXT);`);
    const session = db.prepare("INSERT INTO session VALUES(?,?,?,?,?)");
    session.run("root", cwd, "New session", 1000000, null);
    session.run("noise", cwd, "Noise", 1000001, null);
    session.run("child", cwd, "Background review", 1000002, "root");
    const message = db.prepare("INSERT INTO session_message VALUES(?,?,?,?,?)");
    message.run(
      "u1",
      "root",
      "user",
      1,
      JSON.stringify({ text: caveat + "\nAudit the background runner", time: { created: 1 } }),
    );
    message.run(
      "a1",
      "root",
      "assistant",
      2,
      JSON.stringify({
        content: [
          { type: "reasoning", text: "Checking the exit signal" },
          {
            type: "tool",
            id: "tool1",
            name: "read",
            state: {
              status: "completed",
              input: { filePath: "runner.ts" },
              content: [{ type: "text", text: "stored tool output" }],
            },
          },
          { type: "text", text: "The runner waits for its shell" },
        ],
        time: { created: 2 },
      }),
    );
    message.run("n1", "noise", "user", 1, JSON.stringify({ text: plugins }));
    message.run("c1", "child", "user", 1, JSON.stringify({ text: "Check the child" }));
    db.prepare("INSERT INTO message VALUES(?,?,?,?)").run(
      "legacy",
      "root",
      1,
      JSON.stringify({ role: "user" }),
    );
    db.prepare("INSERT INTO part VALUES(?,?,?)").run(
      "legacy-text",
      "legacy",
      JSON.stringify({ type: "text", text: "Duplicate legacy prompt" }),
    );
    if (storage === "v2 only") db.exec("DROP TABLE message; DROP TABLE part");
    db.close();
    const before = await readFile(path);
    const service = await env.start([{ id: "oc", provider: "opencode", homeDir: home }]);
    await service.scan();
    const sessions = (await service.list({ type: "history.list", cwd })).sessions;
    expect(sessions.map((s) => s.title)).toEqual(["Audit the background runner"]);
    const root = sessions[0];
    if (!root) throw new Error("Missing root");
    const sink = memorySink();
    await service.importSession(init(root.id), sink);
    expect(text(sink.items)).toBe(
      "Audit the background runner The runner waits for its shell Check the child",
    );
    expect(
      sink.items.some((i) => i.type === "reasoning" && i.text === "Checking the exit signal"),
    ).toBe(true);
    expect(
      sink.items.some(
        (i) => i.type === "tool_call" && i.call.status === "succeeded" && i.call.title === "read",
      ),
    ).toBe(true);
    expect(
      sink.items.some(
        (i) => i.type === "notice" && i.toolCallId && i.text === "stored tool output",
      ),
    ).toBe(true);
    expect(await readFile(path)).toEqual(before);
  },
);

test("Legacy OpenCode titles and user messages are cleaned through the same importer", async () => {
  const env = await environment();
  cleanup.push(env.close);
  const home = join(env.root, "opencode");
  await jsonl(join(home, "storage/session/project/root.json"), [
    { id: "root", directory: cwd, title: plugins + "\nRepair retries", time: { updated: 1 } },
  ]);
  await jsonl(join(home, "storage/message/root/u1.json"), [{ role: "user", time: { created: 1 } }]);
  await jsonl(join(home, "storage/part/u1/p1.json"), [
    { type: "text", text: plugins + "\nFix retry delays" },
  ]);
  const service = await env.start([{ id: "oc", provider: "opencode", homeDir: home }]);
  await service.scan();
  const sessions = (await service.list({ type: "history.list", cwd })).sessions;
  expect(sessions.map((s) => s.title)).toEqual(["Repair retries"]);
  const root = sessions[0];
  if (!root) throw new Error("Missing root");
  const sink = memorySink();
  await service.importSession(init(root.id), sink);
  expect(text(sink.items)).toBe("Fix retry delays");
});

test("A readable root with an unreadable child is excluded from openable results with an explanation", async () => {
  const env = await environment();
  cleanup.push(env.close);
  const home = join(env.root, "codex");
  await jsonl(join(home, "sessions/root.jsonl"), codexRecords());
  await jsonl(join(home, "sessions/child.jsonl"), [
    {
      type: "session_meta",
      payload: {
        id: otherId,
        cwd,
        parent_thread_id: nativeId,
        history_base: { thread_id: nativeId, ordinal: 5 },
      },
    },
    ...codexRecords().slice(1),
  ]);
  const service = await env.start([{ id: "cx", provider: "codex", homeDir: home }]);
  await service.scan();
  expect((await service.list({ type: "history.list", cwd, openableOnly: true })).sessions).toEqual(
    [],
  );
  expect((await service.list({ type: "history.list", cwd })).sessions[0]?.support).toMatchObject({
    status: "unsupported",
    reason: expect.stringContaining("Part of this session"),
  });
});
