import { DatabaseSync, backup } from "node:sqlite";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { lstat, rm } from "node:fs/promises";
import { pathToFileURL } from "node:url";
const execute = promisify(execFile);
async function walExists(path: string) {
  try {
    await lstat(path + "-wal");
    return true;
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return false;
    throw error;
  }
}
/** Live WAL uses SQLite locks and backup. A closed, checkpointed WAL database can need
 * immutable mode to avoid creating source sidecars. Accept it only if no WAL exists
 * before/after and the source's nanosecond identity is unchanged throughout backup.
 */
export async function backupStore(path: string, target: string) {
  try {
    const source = new DatabaseSync(path, { readOnly: true });
    try {
      await backup(source, target);
    } finally {
      source.close();
    }
    return;
  } catch {
    await rm(target, { force: true });
  }
  if (await walExists(path))
    throw new Error("Read-only live WAL backup failed; no unsafe fallback was used");
  const before = await lstat(path, { bigint: true });
  const uri = pathToFileURL(path);
  uri.search = "mode=ro&immutable=1";
  // This target is generated by mkdtemp; dot-command quoting never includes owner paths.
  const quoted = JSON.stringify(target);
  try {
    await execute("/usr/bin/sqlite3", [uri.href, `.backup ${quoted}`], { maxBuffer: 64 * 1024 });
    const after = await lstat(path, { bigint: true });
    if (
      (await walExists(path)) ||
      before.mtimeNs !== after.mtimeNs ||
      before.ctimeNs !== after.ctimeNs ||
      before.size !== after.size ||
      before.ino !== after.ino
    )
      throw new Error("Checkpointed source changed during backup");
  } catch (error) {
    await rm(target, { force: true });
    throw error;
  }
}
