import type { ProviderIntegrationCapabilities, ProviderKind } from "@ace/contracts";

type ProviderCapabilitiesOverride = Partial<ProviderIntegrationCapabilities>;

const PROVIDER_INTEGRATION_CAPABILITIES: Record<ProviderKind, ProviderIntegrationCapabilities> = {
  codex: {
    sessionModelSwitch: "in-session",
    sessionModelOptionsSwitch: "in-session",
    liveTurnDiffMode: "native",
    reviewChangesMode: "provider",
    reviewSurface: "turn-native",
    approvalRequestsMode: "native",
    turnSteeringMode: "native",
    transcriptAuthority: "provider",
    historyAuthority: "provider-session",
    sessionResumeMode: "native",
    sessionForkMode: "native",
    sideConversationMode: "native-fork",
    sideConversationCommands: [],
    providerThreadTargetingMode: "native",
    goalControlMode: "native",
    multiAgentMode: "native",
    multiAgentInvocationPrefixes: ["@"],
    multiAgentDefinitionPaths: [
      ".codex/agents",
      "~/.codex/agents",
      "built-in: default",
      "built-in: worker",
      "built-in: explorer",
    ],
    multiAgentManagementCommands: [],
    hookMode: "native",
    extensionMode: "native",
    mcpMode: "native",
    remoteAgentMode: "native",
    webAccessMode: "native",
    hostedSessionMode: "native",
  },
  claudeAgent: {
    sessionModelSwitch: "in-session",
    sessionModelOptionsSwitch: "restart-session",
    liveTurnDiffMode: "reconstructed",
    reviewChangesMode: "provider",
    reviewSurface: "git-worktree",
    approvalRequestsMode: "native",
    turnSteeringMode: "queued-message",
    transcriptAuthority: "provider",
    historyAuthority: "provider-session",
    sessionResumeMode: "native",
    sessionForkMode: "native",
    sideConversationMode: "native-fork",
    sideConversationCommands: [],
    providerThreadTargetingMode: "unsupported",
    goalControlMode: "unsupported",
    multiAgentMode: "native",
    multiAgentInvocationPrefixes: ["@", "@agent-"],
    multiAgentDefinitionPaths: [
      ".claude/agents",
      "~/.claude/agents",
      "built-in: explore",
      "built-in: plan",
      "built-in: general-purpose",
    ],
    multiAgentManagementCommands: ["claude agents", "--agent <agent>", "--agents <json>"],
    hookMode: "native",
    extensionMode: "native",
    mcpMode: "native",
    remoteAgentMode: "unsupported",
    webAccessMode: "native",
    hostedSessionMode: "native",
  },
  gemini: {
    sessionModelSwitch: "in-session",
    sessionModelOptionsSwitch: "in-session",
    liveTurnDiffMode: "reconstructed",
    reviewChangesMode: "provider",
    reviewSurface: "editor-native",
    approvalRequestsMode: "native",
    turnSteeringMode: "queued-message",
    transcriptAuthority: "local",
    historyAuthority: "project-local",
    sessionResumeMode: "local-replay",
    sessionForkMode: "local-replay",
    sideConversationMode: "replay-fork",
    sideConversationCommands: [],
    providerThreadTargetingMode: "unsupported",
    goalControlMode: "unsupported",
    multiAgentMode: "native",
    multiAgentInvocationPrefixes: ["@"],
    multiAgentDefinitionPaths: [
      ".gemini/agents/*.md",
      "~/.gemini/agents/*.md",
      "~/.gemini/extensions/*/agents/*.md",
      "built-in: codebase_investigator",
      "built-in: cli_help",
      "built-in: generalist",
      "built-in: browser_agent",
    ],
    multiAgentManagementCommands: [
      "/agents list",
      "/agents reload",
      "/agents refresh",
      "/agents enable <agent-name>",
      "/agents disable <agent-name>",
      "/agents config <agent-name>",
    ],
    hookMode: "native",
    extensionMode: "native",
    mcpMode: "native",
    remoteAgentMode: "native",
    webAccessMode: "native",
    hostedSessionMode: "unsupported",
  },
  cursor: {
    sessionModelSwitch: "restart-session",
    sessionModelOptionsSwitch: "restart-session",
    liveTurnDiffMode: "workspace",
    reviewChangesMode: "git",
    reviewSurface: "pending-changes",
    approvalRequestsMode: "native",
    turnSteeringMode: "queued-message",
    transcriptAuthority: "local",
    historyAuthority: "project-local",
    sessionResumeMode: "local-replay",
    sessionForkMode: "local-replay",
    sideConversationMode: "replay-fork",
    sideConversationCommands: [],
    providerThreadTargetingMode: "unsupported",
    goalControlMode: "unsupported",
    multiAgentMode: "agent-command",
    multiAgentInvocationPrefixes: ["/"],
    multiAgentDefinitionPaths: [
      ".cursor/agents",
      ".cursor/agents/*.md",
      ".claude/agents",
      ".codex/agents",
      "~/.cursor/agents",
      "~/.cursor/agents/*.md",
      "~/.claude/agents",
      "~/.codex/agents",
      "built-in: explore",
      "built-in: bash",
      "built-in: browser",
    ],
    multiAgentManagementCommands: [],
    hookMode: "unsupported",
    extensionMode: "local-discovery",
    mcpMode: "native",
    remoteAgentMode: "unsupported",
    webAccessMode: "native",
    hostedSessionMode: "native",
  },
  pi: {
    sessionModelSwitch: "in-session",
    sessionModelOptionsSwitch: "in-session",
    liveTurnDiffMode: "workspace",
    reviewChangesMode: "git",
    reviewSurface: "git-worktree",
    approvalRequestsMode: "none",
    turnSteeringMode: "native",
    transcriptAuthority: "local",
    historyAuthority: "local-server-session",
    sessionResumeMode: "local-replay",
    sessionForkMode: "local-replay",
    sideConversationMode: "replay-fork",
    sideConversationCommands: [],
    providerThreadTargetingMode: "unsupported",
    goalControlMode: "unsupported",
    multiAgentMode: "agent-command",
    multiAgentInvocationPrefixes: ["@"],
    multiAgentDefinitionPaths: [
      ".pi/agents",
      ".agents",
      "~/.pi/agent/agents",
      "~/.pi/agent/extensions/subagent/agents",
      "built-in: scout",
      "built-in: researcher",
      "built-in: planner",
      "built-in: worker",
      "built-in: reviewer",
      "built-in: debugger",
      "built-in: verifier",
      "built-in: security-auditor",
      "built-in: docs-writer",
      "built-in: refactorer",
      "built-in: context-builder",
      "built-in: oracle",
      "built-in: delegate",
    ],
    multiAgentManagementCommands: [],
    hookMode: "unsupported",
    extensionMode: "native",
    mcpMode: "unsupported",
    remoteAgentMode: "unsupported",
    webAccessMode: "unsupported",
    hostedSessionMode: "unsupported",
  },
  githubCopilot: {
    sessionModelSwitch: "restart-session",
    sessionModelOptionsSwitch: "restart-session",
    liveTurnDiffMode: "workspace",
    reviewChangesMode: "git",
    reviewSurface: "editor-native",
    approvalRequestsMode: "native",
    turnSteeringMode: "queued-message",
    transcriptAuthority: "local",
    historyAuthority: "local-server-session",
    sessionResumeMode: "native",
    sessionForkMode: "local-replay",
    sideConversationMode: "replay-fork",
    sideConversationCommands: [],
    providerThreadTargetingMode: "unsupported",
    goalControlMode: "unsupported",
    multiAgentMode: "native",
    multiAgentInvocationPrefixes: ["@", "/fleet"],
    multiAgentDefinitionPaths: [
      ".github/agents/*.agent.md",
      ".github/agents/*.md",
      ".github/chatmodes/*.chatmode.md",
      ".github-private/agents/*.agent.md",
      ".github-private/agents/*.md",
      ".claude/agents",
      "~/.copilot/agents/*.agent.md",
      "~/.copilot/agents/*.md",
      "~/.copilot/chatmodes/*.chatmode.md",
      "~/.copilot/.github-private/agents/*.agent.md",
      "~/.copilot/.github-private/agents/*.md",
      "~/.github-copilot/agents/*.agent.md",
      "~/.github-copilot/agents/*.md",
      "~/.github-copilot/chatmodes/*.chatmode.md",
      "~/.github-copilot/.github-private/agents/*.agent.md",
      "~/.github-copilot/.github-private/agents/*.md",
      "configured chat.agentFilesLocations",
      "built-in: explore",
      "built-in: task",
      "built-in: general-purpose",
      "built-in: code-review",
      "built-in: research",
      "built-in: rubber-duck",
      "built-in: fleet",
    ],
    multiAgentManagementCommands: ["/agent", "--agent <agent>", "/fleet", "/tasks", "/sidekicks"],
    hookMode: "native",
    extensionMode: "native",
    mcpMode: "native",
    remoteAgentMode: "native",
    webAccessMode: "agent-command",
    hostedSessionMode: "native",
  },
  opencode: {
    sessionModelSwitch: "in-session",
    sessionModelOptionsSwitch: "in-session",
    liveTurnDiffMode: "workspace",
    reviewChangesMode: "git",
    reviewSurface: "git-worktree",
    approvalRequestsMode: "native",
    turnSteeringMode: "queued-message",
    transcriptAuthority: "local",
    historyAuthority: "local-server-session",
    sessionResumeMode: "local-replay",
    sessionForkMode: "local-replay",
    sideConversationMode: "replay-fork",
    sideConversationCommands: [],
    providerThreadTargetingMode: "native",
    goalControlMode: "unsupported",
    multiAgentMode: "native",
    multiAgentInvocationPrefixes: ["@"],
    multiAgentDefinitionPaths: [
      "opencode.json agent",
      "~/.config/opencode/opencode.json agent",
      ".opencode/agent/*.md",
      ".opencode/agents/*.md",
      "~/.config/opencode/agent/*.md",
      "~/.config/opencode/agents/*.md",
      "built-in: general",
      "built-in: explore",
      "built-in: scout",
    ],
    multiAgentManagementCommands: [],
    hookMode: "native",
    extensionMode: "native",
    mcpMode: "native",
    remoteAgentMode: "unsupported",
    webAccessMode: "mcp-or-shell",
    hostedSessionMode: "unsupported",
  },
};

export function defaultProviderIntegrationCapabilities(
  provider: ProviderKind,
): ProviderIntegrationCapabilities {
  return PROVIDER_INTEGRATION_CAPABILITIES[provider];
}

export function resolveProviderIntegrationCapabilities(
  provider: ProviderKind,
  capabilities?: ProviderCapabilitiesOverride | null,
): ProviderIntegrationCapabilities {
  const defaults = defaultProviderIntegrationCapabilities(provider);
  if (!capabilities) {
    return defaults;
  }
  return {
    ...defaults,
    ...capabilities,
    sessionModelSwitch: capabilities.sessionModelSwitch ?? defaults.sessionModelSwitch,
    sessionModelOptionsSwitch:
      capabilities.sessionModelOptionsSwitch ?? defaults.sessionModelOptionsSwitch,
    sideConversationCommands: normalizedProviderSideConversationCommands(
      capabilities.sideConversationCommands ?? defaults.sideConversationCommands,
    ),
    multiAgentInvocationPrefixes: normalizedProviderCapabilityStringList(
      capabilities.multiAgentInvocationPrefixes ?? defaults.multiAgentInvocationPrefixes,
    ),
    multiAgentDefinitionPaths: normalizedProviderCapabilityStringList(
      capabilities.multiAgentDefinitionPaths ?? defaults.multiAgentDefinitionPaths,
    ),
    multiAgentManagementCommands: normalizedProviderCapabilityStringList(
      capabilities.multiAgentManagementCommands ?? defaults.multiAgentManagementCommands,
    ),
  };
}

function normalizedProviderSideConversationCommands(
  _commands: ReadonlyArray<string>,
): ReadonlyArray<string> {
  return [];
}

function normalizedProviderCapabilityStringList(
  values: ReadonlyArray<string>,
): ReadonlyArray<string> {
  const normalized: string[] = [];
  const seen = new Set<string>();
  for (const value of values) {
    const trimmed = value.trim();
    if (!trimmed) {
      continue;
    }
    const key = trimmed.toLowerCase();
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    normalized.push(trimmed);
  }
  return normalized;
}
