[package]
name = "ace-protocol"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ace-checkpoint.workspace = true
ace-core.workspace = true
ace-lsp.workspace = true
ace-project.workspace = true
ace-workspace.workspace = true
serde.workspace = true
serde_json.workspace = true
