/*
 * Headless view logic shared by the web app and the Expo app: status wording, Home ordering and
 * settling, thread cards, work-log and diff summaries, relative time and the Deck model. Pure
 * TypeScript over @ace/protocol and @ace/client types; no React, DOM or platform APIs.
 */
export * from "./accounts.ts";
export * from "./account-threads.ts";
export * from "./agents.ts";
export * from "./arrange.ts";
export * from "./changed-files.ts";
export * from "./checkout.ts";
export * from "./composer-drafts.ts";
export * from "./content-hash.ts";
export * from "./deck.ts";
export * from "./devices.ts";
export * from "./deck-view.ts";
export * from "./deck-gate.ts";
export * from "./deck-agents.ts";
export * from "./deck-start.ts";
export * from "./diff.ts";
export * from "./motion.ts";
export * from "./file-changes.ts";
export * from "./file-tree.ts";
export * from "./first-launch.ts";
export * from "./home-rows.ts";
export * from "./held-order.ts";
export * from "./inline-markdown.ts";
export * from "./limits.ts";
export * from "./models.ts";
export * from "./model-picker.ts";
export * from "./model-label.ts";
export * from "./lru.ts";
export * from "./organizer.ts";
export * from "./organize-patch.ts";
export * from "./permissions.ts";
export * from "./permission-review.ts";
export * from "./plan.ts";
export * from "./profile.ts";
export * from "./project-badge.ts";
export type { Brand } from "./brand-art/index.gen.ts";
export type { BrandArt, BrandGradient, BrandPath } from "./brand-art-types.ts";
export * from "./providers.ts";
export * from "./provider-status.ts";
export * from "./questions.ts";
export * from "./answered-questions.ts";
export * from "./queue.ts";
export * from "./snooze.ts";
export * from "./status.ts";
export * from "./storage.ts";
export * from "./thread-card.ts";
export * from "./thread-state.ts";
export * from "./thread-title.ts";
export * from "./time.ts";
export * from "./turns.ts";
export * from "./turn-activity.ts";
export * from "./thread-ledger.ts";
export * from "./turn-ordinals.ts";
export * from "./turn-digest.ts";
export * from "./jump-window.ts";
export * from "./search-snippet.ts";
export * from "./catch-up.ts";
export * from "./why.ts";
export * from "./work-log.ts";
export * from "./browser-address.ts";
export * from "./checkout-files.ts";
export * from "./projects.ts";
export * from "./usage-cost.ts";
export * from "./usage-days.ts";
export * from "./step-display.ts";
export * from "./tool-labels.ts";
export * from "./error-display.ts";
export * from "./system-events.ts";
export * from "./system-input.ts";
export * from "./approvals.ts";
