import { replayTs } from "../scenarios/replay-sources.ts";

/*
 * What the fake daemon's checkouts hold: the relay monorepo the cold-start and replay threads
 * work in (projects `ace` and `relay`), and a small web app for every other project. Paths feed
 * `@` mention completion and the Files tool's search; contents feed `files.request` downloads.
 */

const lines = (...text: string[]) => `${text.join("\n")}\n`;

const outbox = lines(
  'import type { OutboxMessage, RelaySocket, SyncStore } from "./types.ts";',
  "",
  "/** Messages written while offline, sent in order once the relay socket is back. */",
  "const MAX_BUFFERED = 500;",
  "",
  "export class Outbox {",
  "  private buffer: OutboxMessage[] = [];",
  "  private lastAckedSeq = 0;",
  "  private store: SyncStore;",
  "",
  "  constructor(store: SyncStore) {",
  "    this.store = store;",
  "    this.lastAckedSeq = store.lastAckedSeq();",
  "  }",
  "",
  "  async resume(socket: RelaySocket) {",
  "    // keep the buffer until the daemon confirms the resume",
  '    socket.send({ type: "resume", lastAckedSeq: this.lastAckedSeq });',
  '    const ack = await socket.waitFor("resume.ack");',
  "    if (ack.coldStart) this.store.markBackfillNeeded(ack.headSeq);",
  "    for (const msg of this.buffer) socket.send(msg);",
  "    this.buffer.length = 0;",
  "  }",
  "",
  "  acknowledge(seq: number) {",
  "    if (seq <= this.lastAckedSeq) return;",
  "    this.lastAckedSeq = seq;",
  "    this.store.saveLastAckedSeq(seq);",
  "  }",
  "",
  "  push(message: OutboxMessage) {",
  "    if (this.buffer.length >= MAX_BUFFERED) this.buffer.shift();",
  "    this.buffer.push(message);",
  "  }",
  "}",
);

const socket = lines(
  'import { backoff } from "./backoff.ts";',
  'import type { RelayMessage } from "./types.ts";',
  "",
  "/** One WebSocket to the relay, reopened with backoff after a drop. */",
  "export class RelaySocket {",
  "  private socket: WebSocket | undefined;",
  "  private attempt = 0;",
  "  private readonly url: string;",
  "",
  "  constructor(url: string) {",
  "    this.url = url;",
  "  }",
  "",
  "  open(onMessage: (message: RelayMessage) => void) {",
  "    const socket = new WebSocket(this.url);",
  "    socket.onmessage = (event) => onMessage(JSON.parse(event.data));",
  "    socket.onclose = () => {",
  "      this.attempt += 1;",
  "      setTimeout(() => this.open(onMessage), backoff(this.attempt));",
  "    };",
  "    socket.onopen = () => {",
  "      this.attempt = 0;",
  "    };",
  "    this.socket = socket;",
  "  }",
  "",
  "  send(message: RelayMessage) {",
  "    this.socket?.send(JSON.stringify(message));",
  "  }",
  "}",
);

const readme = lines(
  "# relay",
  "",
  "The sync relay between ace's daemon and its phone and web clients. Every client resumes from",
  "the last sequence number it acknowledged; a client with nothing cached gets a bounded cold",
  "start instead of the whole history.",
  "",
  "## Layout",
  "",
  "| Path | What lives there |",
  "| --- | --- |",
  "| `apps/server` | The relay: replay, cursors and resume tokens |",
  "| `apps/web` | The web client's outbox and socket |",
  "| `apps/mobile` | The phone app's resume path |",
  "| `packages/protocol` | Event and message schemas shared by all three |",
  "",
  "## Running it",
  "",
  "```sh",
  "bun install",
  "bun run dev:relay     # server on :8787, web on :5173",
  "bun run test          # replay and outbox suites",
  "```",
  "",
  "Replay is capped at `COLD_START_WINDOW` events (200) for a cold start; see",
  "`apps/server/src/replay.ts`.",
);

const packageJson = lines(
  "{",
  '  "name": "relay",',
  '  "private": true,',
  '  "type": "module",',
  '  "workspaces": ["apps/*", "packages/*"],',
  '  "scripts": {',
  '    "dev:relay": "bun run --filter @relay/server dev & bun run --filter @relay/web dev",',
  '    "test": "vitest run",',
  '    "typecheck": "tsc -b"',
  "  },",
  '  "devDependencies": {',
  '    "typescript": "^6.0.2",',
  '    "vitest": "^5.0.3"',
  "  }",
  "}",
);

const events = lines(
  'import { z } from "zod";',
  "",
  "/** One event of a thread's log, in the order the daemon wrote it. */",
  "export const ThreadEvent = z.object({",
  "  seq: z.number().int().nonnegative(),",
  "  threadId: z.string(),",
  "  at: z.number(),",
  "  type: z.string(),",
  "  payload: z.unknown(),",
  "});",
  "export type ThreadEvent = z.infer<typeof ThreadEvent>;",
  "",
  "export const ResumeAck = z.object({",
  '  type: z.literal("resume.ack"),',
  "  headSeq: z.number().int(),",
  "  coldStart: z.boolean(),",
  "});",
);

const replaySpec = lines(
  'import { expect, test } from "vitest";',
  'import { replayFrom } from "./replay.ts";',
  'import { threadWith } from "./test-support.ts";',
  "",
  'test("a client resuming from seq 0 gets at most the last 200 events", () => {',
  "  const thread = threadWith(5000);",
  "  const replay = replayFrom(thread, { lastAckedSeq: 0 });",
  "  expect(replay.events).toHaveLength(200);",
  "  expect(replay.coldStart).toBe(true);",
  "});",
  "",
  'test("a client with a cursor gets every event after it", () => {',
  "  const thread = threadWith(300);",
  "  expect(replayFrom(thread, { lastAckedSeq: 250 }).events).toHaveLength(50);",
  "});",
);

const resume = lines(
  'import { Outbox } from "../../web/src/relay/outbox.ts";',
  'import { nativeStore } from "./store.ts";',
  "",
  "/** The phone app reconnects on launch and whenever it returns to the foreground. */",
  'export async function resumeOnLaunch(socket: Parameters<Outbox["resume"]>[0]) {',
  "  const outbox = new Outbox(nativeStore());",
  "  await outbox.resume(socket);",
  "}",
);

const relay: Record<string, string> = {
  "README.md": readme,
  "package.json": packageJson,
  "apps/server/src/replay.ts": replayTs.afterTurn2,
  "apps/server/src/replay.spec.ts": replaySpec,
  "apps/server/src/cursor.ts": lines(
    "/** Where a client is in a thread's log. */",
    "export interface ReplayCursor {",
    "  lastAckedSeq: number;",
    "}",
  ),
  "apps/server/src/resume.ts": lines(
    'import type { ReplayCursor } from "./cursor.ts";',
    "",
    "export function cursorFrom(token: string | undefined): ReplayCursor {",
    "  const seq = Number(token ?? 0);",
    "  return { lastAckedSeq: Number.isInteger(seq) && seq > 0 ? seq : 0 };",
    "}",
  ),
  "apps/web/src/relay/outbox.ts": outbox,
  "apps/web/src/relay/socket.ts": socket,
  "apps/mobile/src/resume.ts": resume,
  "packages/protocol/src/events.ts": events,
  "apps/web/public/logo.svg": lines(
    '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">',
    '  <rect width="64" height="64" rx="14" fill="#1C1C22"/>',
    '  <path d="M20 44 32 18l12 26" fill="none" stroke="#F4F4F6" stroke-width="5" stroke-linejoin="round"/>',
    "</svg>",
  ),
  "apps/web/public/fonts/inter.woff2": "wOF2\u0000\u0001\u0000\u0000\u0000\u0000\u0012\u0034",
};

const webApp: Record<string, string> = {
  "README.md": lines(
    "# checkout",
    "",
    "The storefront's checkout. `bun run dev` serves it on :5173.",
  ),
  "package.json": lines(
    "{",
    '  "name": "checkout",',
    '  "private": true,',
    '  "scripts": { "dev": "vite", "test": "vitest run" }',
    "}",
  ),
  "src/index.ts": lines('export { App } from "./app.tsx";'),
  "src/app.tsx": lines(
    'import { Checkout } from "./checkout/checkout.tsx";',
    "",
    "export function App() {",
    "  return <Checkout />;",
    "}",
  ),
  "src/routes/index.tsx": lines(
    'import { App } from "../app.tsx";',
    "",
    'export const route = { path: "/", component: App };',
  ),
  "src/lib/fetch.ts": lines(
    "/** fetch with a timeout, so a stalled payment API never hangs the page. */",
    "export async function fetchWithin(url: string, ms = 8000): Promise<Response> {",
    "  const controller = new AbortController();",
    "  const timer = setTimeout(() => controller.abort(), ms);",
    "  try {",
    "    return await fetch(url, { signal: controller.signal });",
    "  } finally {",
    "    clearTimeout(timer);",
    "  }",
    "}",
  ),
  "src/checkout/payment-poller.ts": lines(
    'import { fetchWithin } from "../lib/fetch.ts";',
    "",
    "/** Poll a payment until it settles, backing off from 1s to 10s. */",
    'export async function pollPayment(id: string): Promise<"paid" | "failed"> {',
    "  for (let wait = 1000; ; wait = Math.min(wait * 2, 10_000)) {",
    "    const response = await fetchWithin(`/api/payments/${id}`);",
    "    const { status } = await response.json();",
    '    if (status === "paid" || status === "failed") return status;',
    "    await new Promise((resolve) => setTimeout(resolve, wait));",
    "  }",
    "}",
  ),
  "src/checkout/checkout.spec.ts": lines(
    'import { expect, test } from "vitest";',
    "",
    'test("a settled payment stops polling", () => {',
    "  expect(true).toBe(true);",
    "});",
  ),
};

const checkouts: Record<string, Record<string, string>> = { ace: relay, relay };

/** The files of a project's checkout, path → text. */
export function checkoutFiles(workspaceId: string): Readonly<Record<string, string>> {
  return checkouts[workspaceId] ?? webApp;
}
