import type { DaemonCommandIntegration } from "./commands.ts";
import type { Config } from "../config.ts";
import type { CommandHandler } from "../commands.ts";
import type { EngineOptions } from "../engine/index.ts";
import type { discoverProviders } from "@ace/provider-kit/discovery";
import type { Toolkit } from "@ace/mcp-server";
import type { NotificationChannels } from "@ace/notify";
import type { InstanceInput } from "@ace/models";
import type { HealthOptions } from "@ace/diagnostics";
import type { BrowserServiceOptions } from "@ace/browser";
import type { DaemonPreviewOptions } from "../preview.ts";
import type { DaemonReviewOptions } from "../review.ts";
import type { DaemonHistoryOptions } from "../history.ts";
export type DaemonOptions = {
  commands?: DaemonCommandIntegration;
  config?: Config;
  handler?: CommandHandler | undefined;
  engine?: EngineOptions & { adapterDiscovery?: typeof discoverProviders };
  toolkits?: readonly Toolkit[];
  notificationChannels?: Omit<NotificationChannels, "websocket">;
  modelInstances?: readonly InstanceInput[];
  workload?: HealthOptions["workload"];
  browser?: Omit<BrowserServiceOptions, "dataDir" | "onArtifact">;
  preview?: DaemonPreviewOptions;
  review?: DaemonReviewOptions;
  history?: DaemonHistoryOptions;
};
